// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.ModelsRequests
{
    /// <summary>Filter models by use case category</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetCategoryQueryParameterType
    {
        [EnumMember(Value = "programming")]
        #pragma warning disable CS1591
        Programming,
        #pragma warning restore CS1591
        [EnumMember(Value = "roleplay")]
        #pragma warning disable CS1591
        Roleplay,
        #pragma warning restore CS1591
        [EnumMember(Value = "marketing")]
        #pragma warning disable CS1591
        Marketing,
        #pragma warning restore CS1591
        [EnumMember(Value = "marketing/seo")]
        #pragma warning disable CS1591
        MarketingSeo,
        #pragma warning restore CS1591
        [EnumMember(Value = "technology")]
        #pragma warning disable CS1591
        Technology,
        #pragma warning restore CS1591
        [EnumMember(Value = "science")]
        #pragma warning disable CS1591
        Science,
        #pragma warning restore CS1591
        [EnumMember(Value = "translation")]
        #pragma warning disable CS1591
        Translation,
        #pragma warning restore CS1591
        [EnumMember(Value = "legal")]
        #pragma warning disable CS1591
        Legal,
        #pragma warning restore CS1591
        [EnumMember(Value = "finance")]
        #pragma warning disable CS1591
        Finance,
        #pragma warning restore CS1591
        [EnumMember(Value = "health")]
        #pragma warning disable CS1591
        Health,
        #pragma warning restore CS1591
        [EnumMember(Value = "trivia")]
        #pragma warning disable CS1591
        Trivia,
        #pragma warning restore CS1591
        [EnumMember(Value = "academia")]
        #pragma warning disable CS1591
        Academia,
        #pragma warning restore CS1591
    }
}
