// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.OpenRouter.OpenApiClient.ModelsRequests.Item.Item.Endpoints;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.ModelsRequests.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \models\{author}\{slug}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithSlugItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The endpoints property</summary>
        public global::Soenneker.OpenRouter.OpenApiClient.ModelsRequests.Item.Item.Endpoints.EndpointsRequestBuilder Endpoints
        {
            get => new global::Soenneker.OpenRouter.OpenApiClient.ModelsRequests.Item.Item.Endpoints.EndpointsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenRouter.OpenApiClient.ModelsRequests.Item.Item.WithSlugItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSlugItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/models/{author}/{slug}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenRouter.OpenApiClient.ModelsRequests.Item.Item.WithSlugItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSlugItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/models/{author}/{slug}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
