// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Organization.Members
{
    /// <summary>Role of the member in the organization</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MembersGetResponse_data_role
    {
        [EnumMember(Value = "org:admin")]
        #pragma warning disable CS1591
        OrgAdmin,
        #pragma warning restore CS1591
        [EnumMember(Value = "org:member")]
        #pragma warning disable CS1591
        OrgMember,
        #pragma warning restore CS1591
    }
}
