// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Guardrails
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GuardrailsGetResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Array of model canonical_slugs (immutable identifiers)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AllowedModels { get; set; }
#nullable restore
#else
        public List<string> AllowedModels { get; set; }
#endif
        /// <summary>List of allowed provider IDs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AllowedProviders { get; set; }
#nullable restore
#else
        public List<string> AllowedProviders { get; set; }
#endif
        /// <summary>ISO 8601 timestamp of when the guardrail was created</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>Description of the guardrail</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Whether to enforce zero data retention</summary>
        public bool? EnforceZdr { get; set; }
        /// <summary>Unique identifier for the guardrail</summary>
        public Guid? Id { get; set; }
        /// <summary>List of provider IDs to exclude from routing</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? IgnoredProviders { get; set; }
#nullable restore
#else
        public List<string> IgnoredProviders { get; set; }
#endif
        /// <summary>Spending limit in USD</summary>
        public double? LimitUsd { get; set; }
        /// <summary>Name of the guardrail</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Interval at which the limit resets (daily, weekly, monthly)</summary>
        public global::Soenneker.OpenRouter.OpenApiClient.Guardrails.GuardrailsGetResponse_data_reset_interval? ResetInterval { get; set; }
        /// <summary>ISO 8601 timestamp of when the guardrail was last updated</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenRouter.OpenApiClient.Guardrails.GuardrailsGetResponse_data"/> and sets the default values.
        /// </summary>
        public GuardrailsGetResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenRouter.OpenApiClient.Guardrails.GuardrailsGetResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenRouter.OpenApiClient.Guardrails.GuardrailsGetResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenRouter.OpenApiClient.Guardrails.GuardrailsGetResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowed_models", n => { AllowedModels = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "allowed_providers", n => { AllowedProviders = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "enforce_zdr", n => { EnforceZdr = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "ignored_providers", n => { IgnoredProviders = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "limit_usd", n => { LimitUsd = n.GetDoubleValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "reset_interval", n => { ResetInterval = n.GetEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Guardrails.GuardrailsGetResponse_data_reset_interval>(); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("allowed_models", AllowedModels);
            writer.WriteCollectionOfPrimitiveValues<string>("allowed_providers", AllowedProviders);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteStringValue("description", Description);
            writer.WriteBoolValue("enforce_zdr", EnforceZdr);
            writer.WriteGuidValue("id", Id);
            writer.WriteCollectionOfPrimitiveValues<string>("ignored_providers", IgnoredProviders);
            writer.WriteDoubleValue("limit_usd", LimitUsd);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Guardrails.GuardrailsGetResponse_data_reset_interval>("reset_interval", ResetInterval);
            writer.WriteStringValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
