// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Auth.Keys
{
    /// <summary>The method used to generate the code challenge</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum KeysPostRequestBody_code_challenge_method
    {
        [EnumMember(Value = "S256")]
        #pragma warning disable CS1591
        S256,
        #pragma warning restore CS1591
        [EnumMember(Value = "plain")]
        #pragma warning disable CS1591
        Plain,
        #pragma warning restore CS1591
    }
}
