// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Keys
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class KeysGetResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Total external BYOK usage (in USD) for the API key</summary>
        public double? ByokUsage { get; set; }
        /// <summary>External BYOK usage (in USD) for the current UTC day</summary>
        public double? ByokUsageDaily { get; set; }
        /// <summary>External BYOK usage (in USD) for current UTC month</summary>
        public double? ByokUsageMonthly { get; set; }
        /// <summary>External BYOK usage (in USD) for the current UTC week (Monday-Sunday)</summary>
        public double? ByokUsageWeekly { get; set; }
        /// <summary>ISO 8601 timestamp of when the API key was created</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The user ID of the key creator. For organization-owned keys, this is the member who created the key. For individual users, this is the user&apos;s own ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatorUserId { get; set; }
#nullable restore
#else
        public string CreatorUserId { get; set; }
#endif
        /// <summary>Whether the API key is disabled</summary>
        public bool? Disabled { get; set; }
        /// <summary>ISO 8601 UTC timestamp when the API key expires, or null if no expiration</summary>
        public DateTimeOffset? ExpiresAt { get; set; }
        /// <summary>Unique hash identifier for the API key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Hash { get; set; }
#nullable restore
#else
        public string Hash { get; set; }
#endif
        /// <summary>Whether to include external BYOK usage in the credit limit</summary>
        public bool? IncludeByokInLimit { get; set; }
        /// <summary>Human-readable label for the API key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Label { get; set; }
#nullable restore
#else
        public string Label { get; set; }
#endif
        /// <summary>Spending limit for the API key in USD</summary>
        public double? Limit { get; set; }
        /// <summary>Remaining spending limit in USD</summary>
        public double? LimitRemaining { get; set; }
        /// <summary>Type of limit reset for the API key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LimitReset { get; set; }
#nullable restore
#else
        public string LimitReset { get; set; }
#endif
        /// <summary>Name of the API key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>ISO 8601 timestamp of when the API key was last updated</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>Total OpenRouter credit usage (in USD) for the API key</summary>
        public double? Usage { get; set; }
        /// <summary>OpenRouter credit usage (in USD) for the current UTC day</summary>
        public double? UsageDaily { get; set; }
        /// <summary>OpenRouter credit usage (in USD) for the current UTC month</summary>
        public double? UsageMonthly { get; set; }
        /// <summary>OpenRouter credit usage (in USD) for the current UTC week (Monday-Sunday)</summary>
        public double? UsageWeekly { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenRouter.OpenApiClient.Keys.KeysGetResponse_data"/> and sets the default values.
        /// </summary>
        public KeysGetResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenRouter.OpenApiClient.Keys.KeysGetResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenRouter.OpenApiClient.Keys.KeysGetResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenRouter.OpenApiClient.Keys.KeysGetResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "byok_usage", n => { ByokUsage = n.GetDoubleValue(); } },
                { "byok_usage_daily", n => { ByokUsageDaily = n.GetDoubleValue(); } },
                { "byok_usage_monthly", n => { ByokUsageMonthly = n.GetDoubleValue(); } },
                { "byok_usage_weekly", n => { ByokUsageWeekly = n.GetDoubleValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "creator_user_id", n => { CreatorUserId = n.GetStringValue(); } },
                { "disabled", n => { Disabled = n.GetBoolValue(); } },
                { "expires_at", n => { ExpiresAt = n.GetDateTimeOffsetValue(); } },
                { "hash", n => { Hash = n.GetStringValue(); } },
                { "include_byok_in_limit", n => { IncludeByokInLimit = n.GetBoolValue(); } },
                { "label", n => { Label = n.GetStringValue(); } },
                { "limit", n => { Limit = n.GetDoubleValue(); } },
                { "limit_remaining", n => { LimitRemaining = n.GetDoubleValue(); } },
                { "limit_reset", n => { LimitReset = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
                { "usage", n => { Usage = n.GetDoubleValue(); } },
                { "usage_daily", n => { UsageDaily = n.GetDoubleValue(); } },
                { "usage_monthly", n => { UsageMonthly = n.GetDoubleValue(); } },
                { "usage_weekly", n => { UsageWeekly = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("byok_usage", ByokUsage);
            writer.WriteDoubleValue("byok_usage_daily", ByokUsageDaily);
            writer.WriteDoubleValue("byok_usage_monthly", ByokUsageMonthly);
            writer.WriteDoubleValue("byok_usage_weekly", ByokUsageWeekly);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteStringValue("creator_user_id", CreatorUserId);
            writer.WriteBoolValue("disabled", Disabled);
            writer.WriteDateTimeOffsetValue("expires_at", ExpiresAt);
            writer.WriteStringValue("hash", Hash);
            writer.WriteBoolValue("include_byok_in_limit", IncludeByokInLimit);
            writer.WriteStringValue("label", Label);
            writer.WriteDoubleValue("limit", Limit);
            writer.WriteDoubleValue("limit_remaining", LimitRemaining);
            writer.WriteStringValue("limit_reset", LimitReset);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("updated_at", UpdatedAt);
            writer.WriteDoubleValue("usage", Usage);
            writer.WriteDoubleValue("usage_daily", UsageDaily);
            writer.WriteDoubleValue("usage_monthly", UsageMonthly);
            writer.WriteDoubleValue("usage_weekly", UsageWeekly);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
