// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Embeddings
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum EmbeddingsPostResponse_data_object
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "embedding")]
        #pragma warning disable CS1591
        Embedding,
        #pragma warning restore CS1591
    }
}
