// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Embeddings
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum EmbeddingsPostRequestBody_encoding_format
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "float")]
        #pragma warning disable CS1591
        Float,
        #pragma warning restore CS1591
        [EnumMember(Value = "base64")]
        #pragma warning disable CS1591
        Base64,
        #pragma warning restore CS1591
    }
}
