// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicCodeExecution20250825Caller"/>, <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicCodeExecution20260120Caller"/>, <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicDirectCaller"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AnthropicCaller : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicCodeExecution20250825Caller"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicCodeExecution20250825Caller? AnthropicCodeExecution20250825Caller { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicCodeExecution20250825Caller AnthropicCodeExecution20250825Caller { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicCodeExecution20260120Caller"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicCodeExecution20260120Caller? AnthropicCodeExecution20260120Caller { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicCodeExecution20260120Caller AnthropicCodeExecution20260120Caller { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicDirectCaller"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicDirectCaller? AnthropicDirectCaller { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicDirectCaller AnthropicDirectCaller { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicCaller"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicCaller CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicCaller();
            if("code_execution_20250825".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AnthropicCodeExecution20250825Caller = new global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicCodeExecution20250825Caller();
            }
            else if("code_execution_20260120".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AnthropicCodeExecution20260120Caller = new global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicCodeExecution20260120Caller();
            }
            else if("direct".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AnthropicDirectCaller = new global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicDirectCaller();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(AnthropicCodeExecution20250825Caller != null)
            {
                return AnthropicCodeExecution20250825Caller.GetFieldDeserializers();
            }
            else if(AnthropicCodeExecution20260120Caller != null)
            {
                return AnthropicCodeExecution20260120Caller.GetFieldDeserializers();
            }
            else if(AnthropicDirectCaller != null)
            {
                return AnthropicDirectCaller.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(AnthropicCodeExecution20250825Caller != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicCodeExecution20250825Caller>(null, AnthropicCodeExecution20250825Caller);
            }
            else if(AnthropicCodeExecution20260120Caller != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicCodeExecution20260120Caller>(null, AnthropicCodeExecution20260120Caller);
            }
            else if(AnthropicDirectCaller != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicDirectCaller>(null, AnthropicDirectCaller);
            }
        }
    }
}
#pragma warning restore CS0618
