// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AnthropicToolSearchToolResult_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "tool_search_tool_result")]
        #pragma warning disable CS1591
        Tool_search_tool_result,
        #pragma warning restore CS1591
    }
}
