// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AnthropicCitationWebSearchResultLocation_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "web_search_result_location")]
        #pragma warning disable CS1591
        Web_search_result_location,
        #pragma warning restore CS1591
    }
}
