// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ApplyPatchUpdateFileOperation_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "update_file")]
        #pragma warning disable CS1591
        Update_file,
        #pragma warning restore CS1591
    }
}
