// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum BaseMessagesResult_contentMember10_contentMember1_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "text_editor_code_execution_tool_result_error")]
        #pragma warning disable CS1591
        Text_editor_code_execution_tool_result_error,
        #pragma warning restore CS1591
    }
}
