// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BYOKKey : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Optional allowlist of OpenRouter API key hashes (`api_keys.hash`) that may use this credential. `null` means no restriction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AllowedApiKeyHashes { get; set; }
#nullable restore
#else
        public List<string> AllowedApiKeyHashes { get; set; }
#endif
        /// <summary>Optional allowlist of model slugs this credential may be used for. `null` means no restriction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AllowedModels { get; set; }
#nullable restore
#else
        public List<string> AllowedModels { get; set; }
#endif
        /// <summary>Optional allowlist of user IDs that may use this credential. `null` means no restriction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AllowedUserIds { get; set; }
#nullable restore
#else
        public List<string> AllowedUserIds { get; set; }
#endif
        /// <summary>ISO timestamp of when the credential was created.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>Whether this credential is currently disabled.</summary>
        public bool? Disabled { get; set; }
        /// <summary>Stable public identifier for this BYOK credential.</summary>
        public Guid? Id { get; set; }
        /// <summary>Whether this credential is treated as a fallback — used only after non-fallback keys for the same provider have been tried.</summary>
        public bool? IsFallback { get; set; }
        /// <summary>Short masked snippet of the key (e.g. the first/last few characters) used to identify it in the UI.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Label { get; set; }
#nullable restore
#else
        public string Label { get; set; }
#endif
        /// <summary>Optional human-readable name for the credential.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The upstream provider this credential authenticates against, as a lowercase slug (e.g. `openai`, `anthropic`, `amazon-bedrock`).</summary>
        public global::Soenneker.OpenRouter.OpenApiClient.Models.BYOKProviderSlug? Provider { get; set; }
        /// <summary>Position within the provider — credentials are tried in ascending sort order.</summary>
        public int? SortOrder { get; set; }
        /// <summary>ID of the workspace this credential belongs to.</summary>
        public Guid? WorkspaceId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.BYOKKey"/> and sets the default values.
        /// </summary>
        public BYOKKey()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.BYOKKey"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenRouter.OpenApiClient.Models.BYOKKey CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenRouter.OpenApiClient.Models.BYOKKey();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowed_api_key_hashes", n => { AllowedApiKeyHashes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "allowed_models", n => { AllowedModels = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "allowed_user_ids", n => { AllowedUserIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "disabled", n => { Disabled = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "is_fallback", n => { IsFallback = n.GetBoolValue(); } },
                { "label", n => { Label = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "provider", n => { Provider = n.GetEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.BYOKProviderSlug>(); } },
                { "sort_order", n => { SortOrder = n.GetIntValue(); } },
                { "workspace_id", n => { WorkspaceId = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("allowed_api_key_hashes", AllowedApiKeyHashes);
            writer.WriteCollectionOfPrimitiveValues<string>("allowed_models", AllowedModels);
            writer.WriteCollectionOfPrimitiveValues<string>("allowed_user_ids", AllowedUserIds);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteBoolValue("disabled", Disabled);
            writer.WriteGuidValue("id", Id);
            writer.WriteBoolValue("is_fallback", IsFallback);
            writer.WriteStringValue("label", Label);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.BYOKProviderSlug>("provider", Provider);
            writer.WriteIntValue("sort_order", SortOrder);
            writer.WriteGuidValue("workspace_id", WorkspaceId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
