// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    /// <summary>The upstream provider this credential authenticates against, as a lowercase slug (e.g. `openai`, `anthropic`, `amazon-bedrock`).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BYOKProviderSlug
    {
        [EnumMember(Value = "ai21")]
        #pragma warning disable CS1591
        Ai21,
        #pragma warning restore CS1591
        [EnumMember(Value = "aion-labs")]
        #pragma warning disable CS1591
        AionLabs,
        #pragma warning restore CS1591
        [EnumMember(Value = "akashml")]
        #pragma warning disable CS1591
        Akashml,
        #pragma warning restore CS1591
        [EnumMember(Value = "alibaba")]
        #pragma warning disable CS1591
        Alibaba,
        #pragma warning restore CS1591
        [EnumMember(Value = "amazon-bedrock")]
        #pragma warning disable CS1591
        AmazonBedrock,
        #pragma warning restore CS1591
        [EnumMember(Value = "amazon-nova")]
        #pragma warning disable CS1591
        AmazonNova,
        #pragma warning restore CS1591
        [EnumMember(Value = "ambient")]
        #pragma warning disable CS1591
        Ambient,
        #pragma warning restore CS1591
        [EnumMember(Value = "anthropic")]
        #pragma warning disable CS1591
        Anthropic,
        #pragma warning restore CS1591
        [EnumMember(Value = "arcee-ai")]
        #pragma warning disable CS1591
        ArceeAi,
        #pragma warning restore CS1591
        [EnumMember(Value = "atlas-cloud")]
        #pragma warning disable CS1591
        AtlasCloud,
        #pragma warning restore CS1591
        [EnumMember(Value = "avian")]
        #pragma warning disable CS1591
        Avian,
        #pragma warning restore CS1591
        [EnumMember(Value = "azure")]
        #pragma warning disable CS1591
        Azure,
        #pragma warning restore CS1591
        [EnumMember(Value = "baidu")]
        #pragma warning disable CS1591
        Baidu,
        #pragma warning restore CS1591
        [EnumMember(Value = "baseten")]
        #pragma warning disable CS1591
        Baseten,
        #pragma warning restore CS1591
        [EnumMember(Value = "black-forest-labs")]
        #pragma warning disable CS1591
        BlackForestLabs,
        #pragma warning restore CS1591
        [EnumMember(Value = "byteplus")]
        #pragma warning disable CS1591
        Byteplus,
        #pragma warning restore CS1591
        [EnumMember(Value = "cerebras")]
        #pragma warning disable CS1591
        Cerebras,
        #pragma warning restore CS1591
        [EnumMember(Value = "chutes")]
        #pragma warning disable CS1591
        Chutes,
        #pragma warning restore CS1591
        [EnumMember(Value = "cirrascale")]
        #pragma warning disable CS1591
        Cirrascale,
        #pragma warning restore CS1591
        [EnumMember(Value = "clarifai")]
        #pragma warning disable CS1591
        Clarifai,
        #pragma warning restore CS1591
        [EnumMember(Value = "cloudflare")]
        #pragma warning disable CS1591
        Cloudflare,
        #pragma warning restore CS1591
        [EnumMember(Value = "cohere")]
        #pragma warning disable CS1591
        Cohere,
        #pragma warning restore CS1591
        [EnumMember(Value = "crusoe")]
        #pragma warning disable CS1591
        Crusoe,
        #pragma warning restore CS1591
        [EnumMember(Value = "darkbloom")]
        #pragma warning disable CS1591
        Darkbloom,
        #pragma warning restore CS1591
        [EnumMember(Value = "deepinfra")]
        #pragma warning disable CS1591
        Deepinfra,
        #pragma warning restore CS1591
        [EnumMember(Value = "deepseek")]
        #pragma warning disable CS1591
        Deepseek,
        #pragma warning restore CS1591
        [EnumMember(Value = "dekallm")]
        #pragma warning disable CS1591
        Dekallm,
        #pragma warning restore CS1591
        [EnumMember(Value = "digitalocean")]
        #pragma warning disable CS1591
        Digitalocean,
        #pragma warning restore CS1591
        [EnumMember(Value = "featherless")]
        #pragma warning disable CS1591
        Featherless,
        #pragma warning restore CS1591
        [EnumMember(Value = "fireworks")]
        #pragma warning disable CS1591
        Fireworks,
        #pragma warning restore CS1591
        [EnumMember(Value = "friendli")]
        #pragma warning disable CS1591
        Friendli,
        #pragma warning restore CS1591
        [EnumMember(Value = "gmicloud")]
        #pragma warning disable CS1591
        Gmicloud,
        #pragma warning restore CS1591
        [EnumMember(Value = "google-ai-studio")]
        #pragma warning disable CS1591
        GoogleAiStudio,
        #pragma warning restore CS1591
        [EnumMember(Value = "google-vertex")]
        #pragma warning disable CS1591
        GoogleVertex,
        #pragma warning restore CS1591
        [EnumMember(Value = "groq")]
        #pragma warning disable CS1591
        Groq,
        #pragma warning restore CS1591
        [EnumMember(Value = "hyperbolic")]
        #pragma warning disable CS1591
        Hyperbolic,
        #pragma warning restore CS1591
        [EnumMember(Value = "inception")]
        #pragma warning disable CS1591
        Inception,
        #pragma warning restore CS1591
        [EnumMember(Value = "inceptron")]
        #pragma warning disable CS1591
        Inceptron,
        #pragma warning restore CS1591
        [EnumMember(Value = "inference-net")]
        #pragma warning disable CS1591
        InferenceNet,
        #pragma warning restore CS1591
        [EnumMember(Value = "infermatic")]
        #pragma warning disable CS1591
        Infermatic,
        #pragma warning restore CS1591
        [EnumMember(Value = "inflection")]
        #pragma warning disable CS1591
        Inflection,
        #pragma warning restore CS1591
        [EnumMember(Value = "io-net")]
        #pragma warning disable CS1591
        IoNet,
        #pragma warning restore CS1591
        [EnumMember(Value = "ionstream")]
        #pragma warning disable CS1591
        Ionstream,
        #pragma warning restore CS1591
        [EnumMember(Value = "liquid")]
        #pragma warning disable CS1591
        Liquid,
        #pragma warning restore CS1591
        [EnumMember(Value = "mancer")]
        #pragma warning disable CS1591
        Mancer,
        #pragma warning restore CS1591
        [EnumMember(Value = "mara")]
        #pragma warning disable CS1591
        Mara,
        #pragma warning restore CS1591
        [EnumMember(Value = "minimax")]
        #pragma warning disable CS1591
        Minimax,
        #pragma warning restore CS1591
        [EnumMember(Value = "mistral")]
        #pragma warning disable CS1591
        Mistral,
        #pragma warning restore CS1591
        [EnumMember(Value = "modelrun")]
        #pragma warning disable CS1591
        Modelrun,
        #pragma warning restore CS1591
        [EnumMember(Value = "modular")]
        #pragma warning disable CS1591
        Modular,
        #pragma warning restore CS1591
        [EnumMember(Value = "moonshotai")]
        #pragma warning disable CS1591
        Moonshotai,
        #pragma warning restore CS1591
        [EnumMember(Value = "morph")]
        #pragma warning disable CS1591
        Morph,
        #pragma warning restore CS1591
        [EnumMember(Value = "ncompass")]
        #pragma warning disable CS1591
        Ncompass,
        #pragma warning restore CS1591
        [EnumMember(Value = "nebius")]
        #pragma warning disable CS1591
        Nebius,
        #pragma warning restore CS1591
        [EnumMember(Value = "nex-agi")]
        #pragma warning disable CS1591
        NexAgi,
        #pragma warning restore CS1591
        [EnumMember(Value = "nextbit")]
        #pragma warning disable CS1591
        Nextbit,
        #pragma warning restore CS1591
        [EnumMember(Value = "novita")]
        #pragma warning disable CS1591
        Novita,
        #pragma warning restore CS1591
        [EnumMember(Value = "nvidia")]
        #pragma warning disable CS1591
        Nvidia,
        #pragma warning restore CS1591
        [EnumMember(Value = "open-inference")]
        #pragma warning disable CS1591
        OpenInference,
        #pragma warning restore CS1591
        [EnumMember(Value = "openai")]
        #pragma warning disable CS1591
        Openai,
        #pragma warning restore CS1591
        [EnumMember(Value = "parasail")]
        #pragma warning disable CS1591
        Parasail,
        #pragma warning restore CS1591
        [EnumMember(Value = "perceptron")]
        #pragma warning disable CS1591
        Perceptron,
        #pragma warning restore CS1591
        [EnumMember(Value = "perplexity")]
        #pragma warning disable CS1591
        Perplexity,
        #pragma warning restore CS1591
        [EnumMember(Value = "phala")]
        #pragma warning disable CS1591
        Phala,
        #pragma warning restore CS1591
        [EnumMember(Value = "poolside")]
        #pragma warning disable CS1591
        Poolside,
        #pragma warning restore CS1591
        [EnumMember(Value = "recraft")]
        #pragma warning disable CS1591
        Recraft,
        #pragma warning restore CS1591
        [EnumMember(Value = "reka")]
        #pragma warning disable CS1591
        Reka,
        #pragma warning restore CS1591
        [EnumMember(Value = "relace")]
        #pragma warning disable CS1591
        Relace,
        #pragma warning restore CS1591
        [EnumMember(Value = "sambanova")]
        #pragma warning disable CS1591
        Sambanova,
        #pragma warning restore CS1591
        [EnumMember(Value = "seed")]
        #pragma warning disable CS1591
        Seed,
        #pragma warning restore CS1591
        [EnumMember(Value = "siliconflow")]
        #pragma warning disable CS1591
        Siliconflow,
        #pragma warning restore CS1591
        [EnumMember(Value = "sourceful")]
        #pragma warning disable CS1591
        Sourceful,
        #pragma warning restore CS1591
        [EnumMember(Value = "stepfun")]
        #pragma warning disable CS1591
        Stepfun,
        #pragma warning restore CS1591
        [EnumMember(Value = "streamlake")]
        #pragma warning disable CS1591
        Streamlake,
        #pragma warning restore CS1591
        [EnumMember(Value = "switchpoint")]
        #pragma warning disable CS1591
        Switchpoint,
        #pragma warning restore CS1591
        [EnumMember(Value = "together")]
        #pragma warning disable CS1591
        Together,
        #pragma warning restore CS1591
        [EnumMember(Value = "upstage")]
        #pragma warning disable CS1591
        Upstage,
        #pragma warning restore CS1591
        [EnumMember(Value = "venice")]
        #pragma warning disable CS1591
        Venice,
        #pragma warning restore CS1591
        [EnumMember(Value = "wandb")]
        #pragma warning disable CS1591
        Wandb,
        #pragma warning restore CS1591
        [EnumMember(Value = "xai")]
        #pragma warning disable CS1591
        Xai,
        #pragma warning restore CS1591
        [EnumMember(Value = "xiaomi")]
        #pragma warning disable CS1591
        Xiaomi,
        #pragma warning restore CS1591
        [EnumMember(Value = "z-ai")]
        #pragma warning disable CS1591
        ZAi,
        #pragma warning restore CS1591
    }
}
