// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ChatResult_object
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "chat.completion")]
        #pragma warning disable CS1591
        ChatCompletion,
        #pragma warning restore CS1591
    }
}
