// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    /// <summary>
    /// Token usage statistics
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChatUsage : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Number of tokens in the completion</summary>
        public double? CompletionTokens { get; set; }
        /// <summary>Detailed completion token usage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ChatUsage_completion_tokens_details? CompletionTokensDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ChatUsage_completion_tokens_details CompletionTokensDetails { get; set; }
#endif
        /// <summary>Number of tokens in the prompt</summary>
        public double? PromptTokens { get; set; }
        /// <summary>Detailed prompt token usage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ChatUsage_prompt_tokens_details? PromptTokensDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ChatUsage_prompt_tokens_details PromptTokensDetails { get; set; }
#endif
        /// <summary>Total number of tokens</summary>
        public double? TotalTokens { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ChatUsage"/> and sets the default values.
        /// </summary>
        public ChatUsage()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ChatUsage"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenRouter.OpenApiClient.Models.ChatUsage CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenRouter.OpenApiClient.Models.ChatUsage();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "completion_tokens", n => { CompletionTokens = n.GetDoubleValue(); } },
                { "completion_tokens_details", n => { CompletionTokensDetails = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ChatUsage_completion_tokens_details>(global::Soenneker.OpenRouter.OpenApiClient.Models.ChatUsage_completion_tokens_details.CreateFromDiscriminatorValue); } },
                { "prompt_tokens", n => { PromptTokens = n.GetDoubleValue(); } },
                { "prompt_tokens_details", n => { PromptTokensDetails = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ChatUsage_prompt_tokens_details>(global::Soenneker.OpenRouter.OpenApiClient.Models.ChatUsage_prompt_tokens_details.CreateFromDiscriminatorValue); } },
                { "total_tokens", n => { TotalTokens = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("completion_tokens", CompletionTokens);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ChatUsage_completion_tokens_details>("completion_tokens_details", CompletionTokensDetails);
            writer.WriteDoubleValue("prompt_tokens", PromptTokens);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ChatUsage_prompt_tokens_details>("prompt_tokens_details", PromptTokensDetails);
            writer.WriteDoubleValue("total_tokens", TotalTokens);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
