// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ChatSearchModelsServerTool_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "openrouter:experimental__search_models")]
        #pragma warning disable CS1591
        OpenrouterExperimental__search_models,
        #pragma warning restore CS1591
    }
}
