// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    /// <summary>
    /// Web search tool using OpenAI Responses API syntax. Automatically converted to openrouter:web_search.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChatWebSearchShorthand : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Limit search results to these domains. Supported by Exa, Parallel, and most native providers (Anthropic, OpenAI, xAI). Not supported with Firecrawl or Perplexity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AllowedDomains { get; set; }
#nullable restore
#else
        public List<string> AllowedDomains { get; set; }
#endif
        /// <summary>Which search engine to use. &quot;auto&quot; (default) uses native if the provider supports it, otherwise Exa. &quot;native&quot; forces the provider&apos;s built-in search. &quot;exa&quot; forces the Exa search API. &quot;firecrawl&quot; uses Firecrawl (requires BYOK). &quot;parallel&quot; uses the Parallel search API.</summary>
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ChatWebSearchShorthand_engine? Engine { get; set; }
        /// <summary>Exclude search results from these domains. Supported by Exa, Parallel, Anthropic, and xAI. Not supported with Firecrawl, OpenAI (silently ignored), or Perplexity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ExcludedDomains { get; set; }
#nullable restore
#else
        public List<string> ExcludedDomains { get; set; }
#endif
        /// <summary>Maximum number of search results to return per search call. Defaults to 5. Applies to Exa, Firecrawl, and Parallel engines; ignored with native provider search.</summary>
        public double? MaxResults { get; set; }
        /// <summary>Maximum total number of search results across all search calls in a single request. Once this limit is reached, the tool will stop returning new results. Useful for controlling cost and context size in agentic loops.</summary>
        public double? MaxTotalResults { get; set; }
        /// <summary>The parameters property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ChatWebSearchShorthand_parameters? Parameters { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ChatWebSearchShorthand_parameters Parameters { get; set; }
#endif
        /// <summary>How much context to retrieve per result. Defaults to medium (15000 chars). Only applies when using the Exa engine; ignored with native provider search.</summary>
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ChatWebSearchShorthand_search_context_size? SearchContextSize { get; set; }
        /// <summary>The type property</summary>
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ChatWebSearchShorthand_type? Type { get; set; }
        /// <summary>Approximate user location for location-biased results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ChatWebSearchShorthand_user_location? UserLocation { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ChatWebSearchShorthand_user_location UserLocation { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ChatWebSearchShorthand"/> and sets the default values.
        /// </summary>
        public ChatWebSearchShorthand()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ChatWebSearchShorthand"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenRouter.OpenApiClient.Models.ChatWebSearchShorthand CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenRouter.OpenApiClient.Models.ChatWebSearchShorthand();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "allowed_domains", n => { AllowedDomains = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "engine", n => { Engine = n.GetEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ChatWebSearchShorthand_engine>(); } },
                { "excluded_domains", n => { ExcludedDomains = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "max_results", n => { MaxResults = n.GetDoubleValue(); } },
                { "max_total_results", n => { MaxTotalResults = n.GetDoubleValue(); } },
                { "parameters", n => { Parameters = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ChatWebSearchShorthand_parameters>(global::Soenneker.OpenRouter.OpenApiClient.Models.ChatWebSearchShorthand_parameters.CreateFromDiscriminatorValue); } },
                { "search_context_size", n => { SearchContextSize = n.GetEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ChatWebSearchShorthand_search_context_size>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ChatWebSearchShorthand_type>(); } },
                { "user_location", n => { UserLocation = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ChatWebSearchShorthand_user_location>(global::Soenneker.OpenRouter.OpenApiClient.Models.ChatWebSearchShorthand_user_location.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("allowed_domains", AllowedDomains);
            writer.WriteEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ChatWebSearchShorthand_engine>("engine", Engine);
            writer.WriteCollectionOfPrimitiveValues<string>("excluded_domains", ExcludedDomains);
            writer.WriteDoubleValue("max_results", MaxResults);
            writer.WriteDoubleValue("max_total_results", MaxTotalResults);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ChatWebSearchShorthand_parameters>("parameters", Parameters);
            writer.WriteEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ChatWebSearchShorthand_search_context_size>("search_context_size", SearchContextSize);
            writer.WriteEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ChatWebSearchShorthand_type>("type", Type);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ChatWebSearchShorthand_user_location>("user_location", UserLocation);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
