// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ChatFormatJsonSchemaConfig_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "json_schema")]
        #pragma warning disable CS1591
        Json_schema,
        #pragma warning restore CS1591
    }
}
