// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ComputerUseServerTool_environment
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "windows")]
        #pragma warning disable CS1591
        Windows,
        #pragma warning restore CS1591
        [EnumMember(Value = "mac")]
        #pragma warning disable CS1591
        Mac,
        #pragma warning restore CS1591
        [EnumMember(Value = "linux")]
        #pragma warning disable CS1591
        Linux,
        #pragma warning restore CS1591
        [EnumMember(Value = "ubuntu")]
        #pragma warning disable CS1591
        Ubuntu,
        #pragma warning restore CS1591
        [EnumMember(Value = "browser")]
        #pragma warning disable CS1591
        Browser,
        #pragma warning restore CS1591
    }
}
