// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ContextCompressionPlugin_id
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "context-compression")]
        #pragma warning disable CS1591
        ContextCompression,
        #pragma warning restore CS1591
    }
}
