// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum FilePath_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "file_path")]
        #pragma warning disable CS1591
        File_path,
        #pragma warning restore CS1591
    }
}
