// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    /// <summary>
    /// File search tool configuration
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FileSearchServerTool : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The filters property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.FileSearchServerToolFilters? Filters { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.FileSearchServerToolFilters Filters { get; set; }
#endif
        /// <summary>The max_num_results property</summary>
        public int? MaxNumResults { get; set; }
        /// <summary>The ranking_options property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.FileSearchServerToolRankingOptions? RankingOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.FileSearchServerToolRankingOptions RankingOptions { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.OpenRouter.OpenApiClient.Models.FileSearchServerTool_type? Type { get; set; }
        /// <summary>The vector_store_ids property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? VectorStoreIds { get; set; }
#nullable restore
#else
        public List<string> VectorStoreIds { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.FileSearchServerTool"/> and sets the default values.
        /// </summary>
        public FileSearchServerTool()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.FileSearchServerTool"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenRouter.OpenApiClient.Models.FileSearchServerTool CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenRouter.OpenApiClient.Models.FileSearchServerTool();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "filters", n => { Filters = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.FileSearchServerToolFilters>(global::Soenneker.OpenRouter.OpenApiClient.Models.FileSearchServerToolFilters.CreateFromDiscriminatorValue); } },
                { "max_num_results", n => { MaxNumResults = n.GetIntValue(); } },
                { "ranking_options", n => { RankingOptions = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.FileSearchServerToolRankingOptions>(global::Soenneker.OpenRouter.OpenApiClient.Models.FileSearchServerToolRankingOptions.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.FileSearchServerTool_type>(); } },
                { "vector_store_ids", n => { VectorStoreIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.FileSearchServerToolFilters>("filters", Filters);
            writer.WriteIntValue("max_num_results", MaxNumResults);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.FileSearchServerToolRankingOptions>("ranking_options", RankingOptions);
            writer.WriteEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.FileSearchServerTool_type>("type", Type);
            writer.WriteCollectionOfPrimitiveValues<string>("vector_store_ids", VectorStoreIds);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
