// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    /// <summary>Whether this image represents the first or last frame of the video</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum FrameImage_frame_type
    {
        [EnumMember(Value = "first_frame")]
        #pragma warning disable CS1591
        First_frame,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_frame")]
        #pragma warning disable CS1591
        Last_frame,
        #pragma warning restore CS1591
    }
}
