// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    /// <summary>
    /// Image generation tool configuration
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ImageGenerationServerTool : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The background property</summary>
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerTool_background? Background { get; set; }
        /// <summary>The input_fidelity property</summary>
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerTool_input_fidelity? InputFidelity { get; set; }
        /// <summary>The input_image_mask property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerToolInputImageMask? InputImageMask { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerToolInputImageMask InputImageMask { get; set; }
#endif
        /// <summary>The model property</summary>
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerTool_model? Model { get; set; }
        /// <summary>The moderation property</summary>
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerTool_moderation? Moderation { get; set; }
        /// <summary>The output_compression property</summary>
        public int? OutputCompression { get; set; }
        /// <summary>The output_format property</summary>
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerTool_output_format? OutputFormat { get; set; }
        /// <summary>The partial_images property</summary>
        public int? PartialImages { get; set; }
        /// <summary>The quality property</summary>
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerTool_quality? Quality { get; set; }
        /// <summary>The size property</summary>
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerTool_size? Size { get; set; }
        /// <summary>The type property</summary>
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerTool_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerTool"/> and sets the default values.
        /// </summary>
        public ImageGenerationServerTool()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerTool"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerTool CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerTool();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "background", n => { Background = n.GetEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerTool_background>(); } },
                { "input_fidelity", n => { InputFidelity = n.GetEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerTool_input_fidelity>(); } },
                { "input_image_mask", n => { InputImageMask = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerToolInputImageMask>(global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerToolInputImageMask.CreateFromDiscriminatorValue); } },
                { "model", n => { Model = n.GetEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerTool_model>(); } },
                { "moderation", n => { Moderation = n.GetEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerTool_moderation>(); } },
                { "output_compression", n => { OutputCompression = n.GetIntValue(); } },
                { "output_format", n => { OutputFormat = n.GetEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerTool_output_format>(); } },
                { "partial_images", n => { PartialImages = n.GetIntValue(); } },
                { "quality", n => { Quality = n.GetEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerTool_quality>(); } },
                { "size", n => { Size = n.GetEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerTool_size>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerTool_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerTool_background>("background", Background);
            writer.WriteEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerTool_input_fidelity>("input_fidelity", InputFidelity);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerToolInputImageMask>("input_image_mask", InputImageMask);
            writer.WriteEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerTool_model>("model", Model);
            writer.WriteEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerTool_moderation>("moderation", Moderation);
            writer.WriteIntValue("output_compression", OutputCompression);
            writer.WriteEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerTool_output_format>("output_format", OutputFormat);
            writer.WriteIntValue("partial_images", PartialImages);
            writer.WriteEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerTool_quality>("quality", Quality);
            writer.WriteEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerTool_size>("size", Size);
            writer.WriteEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ImageGenerationServerTool_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
