// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ImageGenerationServerTool_model
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "gpt-image-1")]
        #pragma warning disable CS1591
        GptImage1,
        #pragma warning restore CS1591
        [EnumMember(Value = "gpt-image-1-mini")]
        #pragma warning disable CS1591
        GptImage1Mini,
        #pragma warning restore CS1591
    }
}
