// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum McpListToolsItem_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "mcp_list_tools")]
        #pragma warning disable CS1591
        Mcp_list_tools,
        #pragma warning restore CS1591
    }
}
