// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum McpServerTool_connector_id
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "connector_dropbox")]
        #pragma warning disable CS1591
        Connector_dropbox,
        #pragma warning restore CS1591
        [EnumMember(Value = "connector_gmail")]
        #pragma warning disable CS1591
        Connector_gmail,
        #pragma warning restore CS1591
        [EnumMember(Value = "connector_googlecalendar")]
        #pragma warning disable CS1591
        Connector_googlecalendar,
        #pragma warning restore CS1591
        [EnumMember(Value = "connector_googledrive")]
        #pragma warning disable CS1591
        Connector_googledrive,
        #pragma warning restore CS1591
        [EnumMember(Value = "connector_microsoftteams")]
        #pragma warning disable CS1591
        Connector_microsoftteams,
        #pragma warning restore CS1591
        [EnumMember(Value = "connector_outlookcalendar")]
        #pragma warning disable CS1591
        Connector_outlookcalendar,
        #pragma warning restore CS1591
        [EnumMember(Value = "connector_outlookemail")]
        #pragma warning disable CS1591
        Connector_outlookemail,
        #pragma warning restore CS1591
        [EnumMember(Value = "connector_sharepoint")]
        #pragma warning disable CS1591
        Connector_sharepoint,
        #pragma warning restore CS1591
    }
}
