// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MessagesRequest_tool_choiceMember4_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "tool")]
        #pragma warning disable CS1591
        Tool,
        #pragma warning restore CS1591
    }
}
