// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MessagesRequest_toolsMember5_name
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "web_search")]
        #pragma warning disable CS1591
        Web_search,
        #pragma warning restore CS1591
    }
}
