// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MessagesRequest_toolsMember1_cache_control_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ephemeral")]
        #pragma warning disable CS1591
        Ephemeral,
        #pragma warning restore CS1591
    }
}
