// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    /// <summary>Tokenizer type used by the model</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ModelGroup
    {
        [EnumMember(Value = "Router")]
        #pragma warning disable CS1591
        Router,
        #pragma warning restore CS1591
        [EnumMember(Value = "Media")]
        #pragma warning disable CS1591
        Media,
        #pragma warning restore CS1591
        [EnumMember(Value = "Other")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
        [EnumMember(Value = "GPT")]
        #pragma warning disable CS1591
        GPT,
        #pragma warning restore CS1591
        [EnumMember(Value = "Claude")]
        #pragma warning disable CS1591
        Claude,
        #pragma warning restore CS1591
        [EnumMember(Value = "Gemini")]
        #pragma warning disable CS1591
        Gemini,
        #pragma warning restore CS1591
        [EnumMember(Value = "Grok")]
        #pragma warning disable CS1591
        Grok,
        #pragma warning restore CS1591
        [EnumMember(Value = "Cohere")]
        #pragma warning disable CS1591
        Cohere,
        #pragma warning restore CS1591
        [EnumMember(Value = "Nova")]
        #pragma warning disable CS1591
        Nova,
        #pragma warning restore CS1591
        [EnumMember(Value = "Qwen")]
        #pragma warning disable CS1591
        Qwen,
        #pragma warning restore CS1591
        [EnumMember(Value = "Yi")]
        #pragma warning disable CS1591
        Yi,
        #pragma warning restore CS1591
        [EnumMember(Value = "DeepSeek")]
        #pragma warning disable CS1591
        DeepSeek,
        #pragma warning restore CS1591
        [EnumMember(Value = "Mistral")]
        #pragma warning disable CS1591
        Mistral,
        #pragma warning restore CS1591
        [EnumMember(Value = "Llama2")]
        #pragma warning disable CS1591
        Llama2,
        #pragma warning restore CS1591
        [EnumMember(Value = "Llama3")]
        #pragma warning disable CS1591
        Llama3,
        #pragma warning restore CS1591
        [EnumMember(Value = "Llama4")]
        #pragma warning disable CS1591
        Llama4,
        #pragma warning restore CS1591
        [EnumMember(Value = "PaLM")]
        #pragma warning disable CS1591
        PaLM,
        #pragma warning restore CS1591
        [EnumMember(Value = "RWKV")]
        #pragma warning disable CS1591
        RWKV,
        #pragma warning restore CS1591
        [EnumMember(Value = "Qwen3")]
        #pragma warning disable CS1591
        Qwen3,
        #pragma warning restore CS1591
    }
}
