// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ObservabilityClickhouseDestination : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Optional allowlist of OpenRouter API key hashes (`api_keys.hash`) whose traffic is forwarded to this destination. `null` means all keys.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ApiKeyHashes { get; set; }
#nullable restore
#else
        public List<string> ApiKeyHashes { get; set; }
#endif
        /// <summary>The config property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityClickhouseDestinationConfig? Config { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityClickhouseDestinationConfig Config { get; set; }
#endif
        /// <summary>ISO timestamp of when the destination was created.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>Whether this destination is currently enabled.</summary>
        public bool? Enabled { get; set; }
        /// <summary>Optional structured filter rules controlling which events are forwarded.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityFilterRulesConfig? FilterRules { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityFilterRulesConfig FilterRules { get; set; }
#endif
        /// <summary>Stable public identifier for this destination.</summary>
        public Guid? Id { get; set; }
        /// <summary>Human-readable name for the destination.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>When true, request/response bodies are not forwarded to this destination — only metadata.</summary>
        public bool? PrivacyMode { get; set; }
        /// <summary>Sampling rate for events sent to this destination, between 0 and 1 (1 = 100%).</summary>
        public double? SamplingRate { get; set; }
        /// <summary>The type property</summary>
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityClickhouseDestination_type? Type { get; set; }
        /// <summary>ISO timestamp of when the destination was last updated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>ID of the workspace this destination belongs to.</summary>
        public Guid? WorkspaceId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityClickhouseDestination"/> and sets the default values.
        /// </summary>
        public ObservabilityClickhouseDestination()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityClickhouseDestination"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityClickhouseDestination CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityClickhouseDestination();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "api_key_hashes", n => { ApiKeyHashes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "config", n => { Config = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityClickhouseDestinationConfig>(global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityClickhouseDestinationConfig.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "filter_rules", n => { FilterRules = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityFilterRulesConfig>(global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityFilterRulesConfig.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "privacy_mode", n => { PrivacyMode = n.GetBoolValue(); } },
                { "sampling_rate", n => { SamplingRate = n.GetDoubleValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityClickhouseDestination_type>(); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
                { "workspace_id", n => { WorkspaceId = n.GetGuidValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("api_key_hashes", ApiKeyHashes);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityClickhouseDestinationConfig>("config", Config);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityFilterRulesConfig>("filter_rules", FilterRules);
            writer.WriteGuidValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("privacy_mode", PrivacyMode);
            writer.WriteDoubleValue("sampling_rate", SamplingRate);
            writer.WriteEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityClickhouseDestination_type>("type", Type);
            writer.WriteStringValue("updated_at", UpdatedAt);
            writer.WriteGuidValue("workspace_id", WorkspaceId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
