// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ObservabilityDestination : IAdditionalDataHolder, IComposedTypeWrapper, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Optional allowlist of OpenRouter API key hashes (`api_keys.hash`) whose traffic is forwarded to this destination. `null` means all keys.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ApiKeyHashes { get; set; }
#nullable restore
#else
        public List<string> ApiKeyHashes { get; set; }
#endif
        /// <summary>The config property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityArizeDestinationConfig? Config { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityArizeDestinationConfig Config { get; set; }
#endif
        /// <summary>ISO timestamp of when the destination was created.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>Whether this destination is currently enabled.</summary>
        public bool? Enabled { get; set; }
        /// <summary>Optional structured filter rules controlling which events are forwarded.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityFilterRulesConfig? FilterRules { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityFilterRulesConfig FilterRules { get; set; }
#endif
        /// <summary>Stable public identifier for this destination.</summary>
        public Guid? Id { get; set; }
        /// <summary>Human-readable name for the destination.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityArizeDestination"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityArizeDestination? ObservabilityArizeDestination { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityArizeDestination ObservabilityArizeDestination { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityBraintrustDestination"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityBraintrustDestination? ObservabilityBraintrustDestination { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityBraintrustDestination ObservabilityBraintrustDestination { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityClickhouseDestination"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityClickhouseDestination? ObservabilityClickhouseDestination { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityClickhouseDestination ObservabilityClickhouseDestination { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityDatadogDestination"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityDatadogDestination? ObservabilityDatadogDestination { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityDatadogDestination ObservabilityDatadogDestination { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityGrafanaDestination"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityGrafanaDestination? ObservabilityGrafanaDestination { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityGrafanaDestination ObservabilityGrafanaDestination { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityLangfuseDestination"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityLangfuseDestination? ObservabilityLangfuseDestination { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityLangfuseDestination ObservabilityLangfuseDestination { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityLangsmithDestination"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityLangsmithDestination? ObservabilityLangsmithDestination { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityLangsmithDestination ObservabilityLangsmithDestination { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityNewrelicDestination"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityNewrelicDestination? ObservabilityNewrelicDestination { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityNewrelicDestination ObservabilityNewrelicDestination { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityOpikDestination"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityOpikDestination? ObservabilityOpikDestination { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityOpikDestination ObservabilityOpikDestination { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityOtelCollectorDestination"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityOtelCollectorDestination? ObservabilityOtelCollectorDestination { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityOtelCollectorDestination ObservabilityOtelCollectorDestination { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityPosthogDestination"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityPosthogDestination? ObservabilityPosthogDestination { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityPosthogDestination ObservabilityPosthogDestination { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityRampDestination"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityRampDestination? ObservabilityRampDestination { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityRampDestination ObservabilityRampDestination { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityS3Destination"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityS3Destination? ObservabilityS3Destination { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityS3Destination ObservabilityS3Destination { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilitySentryDestination"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilitySentryDestination? ObservabilitySentryDestination { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilitySentryDestination ObservabilitySentryDestination { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilitySnowflakeDestination"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilitySnowflakeDestination? ObservabilitySnowflakeDestination { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilitySnowflakeDestination ObservabilitySnowflakeDestination { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityWeaveDestination"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityWeaveDestination? ObservabilityWeaveDestination { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityWeaveDestination ObservabilityWeaveDestination { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityWebhookDestination"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityWebhookDestination? ObservabilityWebhookDestination { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityWebhookDestination ObservabilityWebhookDestination { get; set; }
#endif
        /// <summary>When true, request/response bodies are not forwarded to this destination — only metadata.</summary>
        public bool? PrivacyMode { get; set; }
        /// <summary>Sampling rate for events sent to this destination, between 0.0001 and 1 (1 = 100%).</summary>
        public double? SamplingRate { get; set; }
        /// <summary>Union discriminator</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>ISO timestamp of when the destination was last updated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>ID of the workspace this destination belongs to.</summary>
        public Guid? WorkspaceId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityDestination"/> and sets the default values.
        /// </summary>
        public ObservabilityDestination()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityDestination"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityDestination CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityDestination();
            if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.Config = new global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityArizeDestinationConfig();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.FilterRules = new global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityFilterRulesConfig();
            }
            else if("arize".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ObservabilityArizeDestination = new global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityArizeDestination();
            }
            else if("braintrust".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ObservabilityBraintrustDestination = new global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityBraintrustDestination();
            }
            else if("clickhouse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ObservabilityClickhouseDestination = new global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityClickhouseDestination();
            }
            else if("datadog".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ObservabilityDatadogDestination = new global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityDatadogDestination();
            }
            else if("grafana".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ObservabilityGrafanaDestination = new global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityGrafanaDestination();
            }
            else if("langfuse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ObservabilityLangfuseDestination = new global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityLangfuseDestination();
            }
            else if("langsmith".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ObservabilityLangsmithDestination = new global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityLangsmithDestination();
            }
            else if("newrelic".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ObservabilityNewrelicDestination = new global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityNewrelicDestination();
            }
            else if("ObservabilityOpikDestination".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ObservabilityOpikDestination = new global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityOpikDestination();
            }
            else if("ObservabilityOtelCollectorDestination".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ObservabilityOtelCollectorDestination = new global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityOtelCollectorDestination();
            }
            else if("ObservabilityPosthogDestination".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ObservabilityPosthogDestination = new global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityPosthogDestination();
            }
            else if("ObservabilityRampDestination".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ObservabilityRampDestination = new global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityRampDestination();
            }
            else if("ObservabilityS3Destination".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ObservabilityS3Destination = new global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityS3Destination();
            }
            else if("ObservabilitySentryDestination".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ObservabilitySentryDestination = new global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilitySentryDestination();
            }
            else if("ObservabilitySnowflakeDestination".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ObservabilitySnowflakeDestination = new global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilitySnowflakeDestination();
            }
            else if("ObservabilityWeaveDestination".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ObservabilityWeaveDestination = new global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityWeaveDestination();
            }
            else if("ObservabilityWebhookDestination".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ObservabilityWebhookDestination = new global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityWebhookDestination();
            }
            else if(parseNode.GetStringValue() is string createdAtValue)
            {
                result.CreatedAt = createdAtValue;
            }
            else if(parseNode.GetBoolValue() is bool enabledValue)
            {
                result.Enabled = enabledValue;
            }
            else if(parseNode.GetGuidValue() is Guid idValue)
            {
                result.Id = idValue;
            }
            else if(parseNode.GetStringValue() is string nameValue)
            {
                result.Name = nameValue;
            }
            else if(parseNode.GetBoolValue() is bool privacyModeValue)
            {
                result.PrivacyMode = privacyModeValue;
            }
            else if(parseNode.GetDoubleValue() is double samplingRateValue)
            {
                result.SamplingRate = samplingRateValue;
            }
            else if(parseNode.GetStringValue() is string typeValue)
            {
                result.Type = typeValue;
            }
            else if(parseNode.GetStringValue() is string updatedAtValue)
            {
                result.UpdatedAt = updatedAtValue;
            }
            else if(parseNode.GetGuidValue() is Guid workspaceIdValue)
            {
                result.WorkspaceId = workspaceIdValue;
            }
            else if(parseNode.GetCollectionOfPrimitiveValues<string>()?.AsList() is List<string> apiKeyHashesValue)
            {
                result.ApiKeyHashes = apiKeyHashesValue;
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(Config != null)
            {
                return Config.GetFieldDeserializers();
            }
            else if(FilterRules != null)
            {
                return FilterRules.GetFieldDeserializers();
            }
            else if(ObservabilityArizeDestination != null)
            {
                return ObservabilityArizeDestination.GetFieldDeserializers();
            }
            else if(ObservabilityBraintrustDestination != null)
            {
                return ObservabilityBraintrustDestination.GetFieldDeserializers();
            }
            else if(ObservabilityClickhouseDestination != null)
            {
                return ObservabilityClickhouseDestination.GetFieldDeserializers();
            }
            else if(ObservabilityDatadogDestination != null)
            {
                return ObservabilityDatadogDestination.GetFieldDeserializers();
            }
            else if(ObservabilityGrafanaDestination != null)
            {
                return ObservabilityGrafanaDestination.GetFieldDeserializers();
            }
            else if(ObservabilityLangfuseDestination != null)
            {
                return ObservabilityLangfuseDestination.GetFieldDeserializers();
            }
            else if(ObservabilityLangsmithDestination != null)
            {
                return ObservabilityLangsmithDestination.GetFieldDeserializers();
            }
            else if(ObservabilityNewrelicDestination != null)
            {
                return ObservabilityNewrelicDestination.GetFieldDeserializers();
            }
            else if(ObservabilityOpikDestination != null)
            {
                return ObservabilityOpikDestination.GetFieldDeserializers();
            }
            else if(ObservabilityOtelCollectorDestination != null)
            {
                return ObservabilityOtelCollectorDestination.GetFieldDeserializers();
            }
            else if(ObservabilityPosthogDestination != null)
            {
                return ObservabilityPosthogDestination.GetFieldDeserializers();
            }
            else if(ObservabilityRampDestination != null)
            {
                return ObservabilityRampDestination.GetFieldDeserializers();
            }
            else if(ObservabilityS3Destination != null)
            {
                return ObservabilityS3Destination.GetFieldDeserializers();
            }
            else if(ObservabilitySentryDestination != null)
            {
                return ObservabilitySentryDestination.GetFieldDeserializers();
            }
            else if(ObservabilitySnowflakeDestination != null)
            {
                return ObservabilitySnowflakeDestination.GetFieldDeserializers();
            }
            else if(ObservabilityWeaveDestination != null)
            {
                return ObservabilityWeaveDestination.GetFieldDeserializers();
            }
            else if(ObservabilityWebhookDestination != null)
            {
                return ObservabilityWebhookDestination.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(Config != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityArizeDestinationConfig>(null, Config);
            }
            else if(FilterRules != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityFilterRulesConfig>(null, FilterRules);
            }
            else if(ObservabilityArizeDestination != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityArizeDestination>(null, ObservabilityArizeDestination);
            }
            else if(ObservabilityBraintrustDestination != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityBraintrustDestination>(null, ObservabilityBraintrustDestination);
            }
            else if(ObservabilityClickhouseDestination != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityClickhouseDestination>(null, ObservabilityClickhouseDestination);
            }
            else if(ObservabilityDatadogDestination != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityDatadogDestination>(null, ObservabilityDatadogDestination);
            }
            else if(ObservabilityGrafanaDestination != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityGrafanaDestination>(null, ObservabilityGrafanaDestination);
            }
            else if(ObservabilityLangfuseDestination != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityLangfuseDestination>(null, ObservabilityLangfuseDestination);
            }
            else if(ObservabilityLangsmithDestination != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityLangsmithDestination>(null, ObservabilityLangsmithDestination);
            }
            else if(ObservabilityNewrelicDestination != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityNewrelicDestination>(null, ObservabilityNewrelicDestination);
            }
            else if(ObservabilityOpikDestination != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityOpikDestination>(null, ObservabilityOpikDestination);
            }
            else if(ObservabilityOtelCollectorDestination != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityOtelCollectorDestination>(null, ObservabilityOtelCollectorDestination);
            }
            else if(ObservabilityPosthogDestination != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityPosthogDestination>(null, ObservabilityPosthogDestination);
            }
            else if(ObservabilityRampDestination != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityRampDestination>(null, ObservabilityRampDestination);
            }
            else if(ObservabilityS3Destination != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityS3Destination>(null, ObservabilityS3Destination);
            }
            else if(ObservabilitySentryDestination != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilitySentryDestination>(null, ObservabilitySentryDestination);
            }
            else if(ObservabilitySnowflakeDestination != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilitySnowflakeDestination>(null, ObservabilitySnowflakeDestination);
            }
            else if(ObservabilityWeaveDestination != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityWeaveDestination>(null, ObservabilityWeaveDestination);
            }
            else if(ObservabilityWebhookDestination != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ObservabilityWebhookDestination>(null, ObservabilityWebhookDestination);
            }
            else if(CreatedAt != null)
            {
                writer.WriteStringValue(null, CreatedAt);
            }
            else if(Enabled != null)
            {
                writer.WriteBoolValue(null, Enabled);
            }
            else if(Id != null)
            {
                writer.WriteGuidValue(null, Id);
            }
            else if(Name != null)
            {
                writer.WriteStringValue(null, Name);
            }
            else if(PrivacyMode != null)
            {
                writer.WriteBoolValue(null, PrivacyMode);
            }
            else if(SamplingRate != null)
            {
                writer.WriteDoubleValue(null, SamplingRate);
            }
            else if(Type != null)
            {
                writer.WriteStringValue(null, Type);
            }
            else if(UpdatedAt != null)
            {
                writer.WriteStringValue(null, UpdatedAt);
            }
            else if(WorkspaceId != null)
            {
                writer.WriteGuidValue(null, WorkspaceId);
            }
            else if(ApiKeyHashes != null)
            {
                writer.WriteCollectionOfPrimitiveValues<string>(null, ApiKeyHashes);
            }
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
