// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class OpenAIResponseInputMessageItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The content property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenRouter.OpenApiClient.Models.OpenAIResponseInputMessageItem.OpenAIResponseInputMessageItem_content>? Content { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenRouter.OpenApiClient.Models.OpenAIResponseInputMessageItem.OpenAIResponseInputMessageItem_content> Content { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The role property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.UnionBranch? Role { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.UnionBranch Role { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.OpenRouter.OpenApiClient.Models.OpenAIResponseInputMessageItem_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.OpenAIResponseInputMessageItem"/> and sets the default values.
        /// </summary>
        public OpenAIResponseInputMessageItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.OpenAIResponseInputMessageItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenRouter.OpenApiClient.Models.OpenAIResponseInputMessageItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenRouter.OpenApiClient.Models.OpenAIResponseInputMessageItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "content", n => { Content = n.GetCollectionOfObjectValues<global::Soenneker.OpenRouter.OpenApiClient.Models.OpenAIResponseInputMessageItem.OpenAIResponseInputMessageItem_content>(global::Soenneker.OpenRouter.OpenApiClient.Models.OpenAIResponseInputMessageItem.OpenAIResponseInputMessageItem_content.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "role", n => { Role = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.UnionBranch>(global::Soenneker.OpenRouter.OpenApiClient.Models.UnionBranch.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.OpenAIResponseInputMessageItem_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenRouter.OpenApiClient.Models.OpenAIResponseInputMessageItem.OpenAIResponseInputMessageItem_content>("content", Content);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.UnionBranch>("role", Role);
            writer.WriteEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.OpenAIResponseInputMessageItem_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.InputAudio"/>, <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.InputFile"/>, <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.InputImage"/>, <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.InputText"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OpenAIResponseInputMessageItem_content : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.InputAudio"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenRouter.OpenApiClient.Models.InputAudio? InputAudio { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenRouter.OpenApiClient.Models.InputAudio InputAudio { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.InputFile"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenRouter.OpenApiClient.Models.InputFile? InputFile { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenRouter.OpenApiClient.Models.InputFile InputFile { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.InputImage"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenRouter.OpenApiClient.Models.InputImage? InputImage { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenRouter.OpenApiClient.Models.InputImage InputImage { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.InputText"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.OpenRouter.OpenApiClient.Models.InputText? InputText { get; set; }
#nullable restore
#else
            public global::Soenneker.OpenRouter.OpenApiClient.Models.InputText InputText { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.OpenAIResponseInputMessageItem.OpenAIResponseInputMessageItem_content"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenRouter.OpenApiClient.Models.OpenAIResponseInputMessageItem.OpenAIResponseInputMessageItem_content CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
                var result = new global::Soenneker.OpenRouter.OpenApiClient.Models.OpenAIResponseInputMessageItem.OpenAIResponseInputMessageItem_content();
                if("input_audio".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.InputAudio = new global::Soenneker.OpenRouter.OpenApiClient.Models.InputAudio();
                }
                else if("input_file".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.InputFile = new global::Soenneker.OpenRouter.OpenApiClient.Models.InputFile();
                }
                else if("input_image".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.InputImage = new global::Soenneker.OpenRouter.OpenApiClient.Models.InputImage();
                }
                else if("input_text".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.InputText = new global::Soenneker.OpenRouter.OpenApiClient.Models.InputText();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(InputAudio != null)
                {
                    return InputAudio.GetFieldDeserializers();
                }
                else if(InputFile != null)
                {
                    return InputFile.GetFieldDeserializers();
                }
                else if(InputImage != null)
                {
                    return InputImage.GetFieldDeserializers();
                }
                else if(InputText != null)
                {
                    return InputText.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(InputAudio != null)
                {
                    writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.InputAudio>(null, InputAudio);
                }
                else if(InputFile != null)
                {
                    writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.InputFile>(null, InputFile);
                }
                else if(InputImage != null)
                {
                    writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.InputImage>(null, InputImage);
                }
                else if(InputText != null)
                {
                    writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.InputText>(null, InputText);
                }
            }
        }
    }
}
#pragma warning restore CS0618
