// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicBashCodeExecutionToolResult"/>, <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicCodeExecutionToolResult"/>, <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicCompactionBlock"/>, <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicContainerUpload"/>, <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicRedactedThinkingBlock"/>, <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicServerToolUseBlock"/>, <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicTextBlock"/>, <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicTextEditorCodeExecutionToolResult"/>, <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicThinkingBlock"/>, <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicToolSearchToolResult"/>, <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicToolUseBlock"/>, <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicWebFetchToolResult"/>, <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicWebSearchToolResult"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ORAnthropicContentBlock : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicBashCodeExecutionToolResult"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicBashCodeExecutionToolResult? AnthropicBashCodeExecutionToolResult { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicBashCodeExecutionToolResult AnthropicBashCodeExecutionToolResult { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicCodeExecutionToolResult"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicCodeExecutionToolResult? AnthropicCodeExecutionToolResult { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicCodeExecutionToolResult AnthropicCodeExecutionToolResult { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicCompactionBlock"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicCompactionBlock? AnthropicCompactionBlock { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicCompactionBlock AnthropicCompactionBlock { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicContainerUpload"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicContainerUpload? AnthropicContainerUpload { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicContainerUpload AnthropicContainerUpload { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicRedactedThinkingBlock"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicRedactedThinkingBlock? AnthropicRedactedThinkingBlock { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicRedactedThinkingBlock AnthropicRedactedThinkingBlock { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicServerToolUseBlock"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicServerToolUseBlock? AnthropicServerToolUseBlock { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicServerToolUseBlock AnthropicServerToolUseBlock { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicTextBlock"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicTextBlock? AnthropicTextBlock { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicTextBlock AnthropicTextBlock { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicTextEditorCodeExecutionToolResult"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicTextEditorCodeExecutionToolResult? AnthropicTextEditorCodeExecutionToolResult { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicTextEditorCodeExecutionToolResult AnthropicTextEditorCodeExecutionToolResult { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicThinkingBlock"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicThinkingBlock? AnthropicThinkingBlock { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicThinkingBlock AnthropicThinkingBlock { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicToolSearchToolResult"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicToolSearchToolResult? AnthropicToolSearchToolResult { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicToolSearchToolResult AnthropicToolSearchToolResult { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicToolUseBlock"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicToolUseBlock? AnthropicToolUseBlock { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicToolUseBlock AnthropicToolUseBlock { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicWebFetchToolResult"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicWebFetchToolResult? AnthropicWebFetchToolResult { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicWebFetchToolResult AnthropicWebFetchToolResult { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicWebSearchToolResult"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicWebSearchToolResult? AnthropicWebSearchToolResult { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicWebSearchToolResult AnthropicWebSearchToolResult { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ORAnthropicContentBlock"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenRouter.OpenApiClient.Models.ORAnthropicContentBlock CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.OpenRouter.OpenApiClient.Models.ORAnthropicContentBlock();
            if("bash_code_execution_tool_result".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AnthropicBashCodeExecutionToolResult = new global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicBashCodeExecutionToolResult();
            }
            else if("code_execution_tool_result".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AnthropicCodeExecutionToolResult = new global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicCodeExecutionToolResult();
            }
            else if("compaction".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AnthropicCompactionBlock = new global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicCompactionBlock();
            }
            else if("container_upload".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AnthropicContainerUpload = new global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicContainerUpload();
            }
            else if("redacted_thinking".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AnthropicRedactedThinkingBlock = new global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicRedactedThinkingBlock();
            }
            else if("server_tool_use".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AnthropicServerToolUseBlock = new global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicServerToolUseBlock();
            }
            else if("text".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AnthropicTextBlock = new global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicTextBlock();
            }
            else if("text_editor_code_execution_tool_result".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AnthropicTextEditorCodeExecutionToolResult = new global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicTextEditorCodeExecutionToolResult();
            }
            else if("thinking".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AnthropicThinkingBlock = new global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicThinkingBlock();
            }
            else if("tool_search_tool_result".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AnthropicToolSearchToolResult = new global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicToolSearchToolResult();
            }
            else if("tool_use".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AnthropicToolUseBlock = new global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicToolUseBlock();
            }
            else if("web_fetch_tool_result".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AnthropicWebFetchToolResult = new global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicWebFetchToolResult();
            }
            else if("web_search_tool_result".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AnthropicWebSearchToolResult = new global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicWebSearchToolResult();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(AnthropicBashCodeExecutionToolResult != null)
            {
                return AnthropicBashCodeExecutionToolResult.GetFieldDeserializers();
            }
            else if(AnthropicCodeExecutionToolResult != null)
            {
                return AnthropicCodeExecutionToolResult.GetFieldDeserializers();
            }
            else if(AnthropicCompactionBlock != null)
            {
                return AnthropicCompactionBlock.GetFieldDeserializers();
            }
            else if(AnthropicContainerUpload != null)
            {
                return AnthropicContainerUpload.GetFieldDeserializers();
            }
            else if(AnthropicRedactedThinkingBlock != null)
            {
                return AnthropicRedactedThinkingBlock.GetFieldDeserializers();
            }
            else if(AnthropicServerToolUseBlock != null)
            {
                return AnthropicServerToolUseBlock.GetFieldDeserializers();
            }
            else if(AnthropicTextBlock != null)
            {
                return AnthropicTextBlock.GetFieldDeserializers();
            }
            else if(AnthropicTextEditorCodeExecutionToolResult != null)
            {
                return AnthropicTextEditorCodeExecutionToolResult.GetFieldDeserializers();
            }
            else if(AnthropicThinkingBlock != null)
            {
                return AnthropicThinkingBlock.GetFieldDeserializers();
            }
            else if(AnthropicToolSearchToolResult != null)
            {
                return AnthropicToolSearchToolResult.GetFieldDeserializers();
            }
            else if(AnthropicToolUseBlock != null)
            {
                return AnthropicToolUseBlock.GetFieldDeserializers();
            }
            else if(AnthropicWebFetchToolResult != null)
            {
                return AnthropicWebFetchToolResult.GetFieldDeserializers();
            }
            else if(AnthropicWebSearchToolResult != null)
            {
                return AnthropicWebSearchToolResult.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(AnthropicBashCodeExecutionToolResult != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicBashCodeExecutionToolResult>(null, AnthropicBashCodeExecutionToolResult);
            }
            else if(AnthropicCodeExecutionToolResult != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicCodeExecutionToolResult>(null, AnthropicCodeExecutionToolResult);
            }
            else if(AnthropicCompactionBlock != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicCompactionBlock>(null, AnthropicCompactionBlock);
            }
            else if(AnthropicContainerUpload != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicContainerUpload>(null, AnthropicContainerUpload);
            }
            else if(AnthropicRedactedThinkingBlock != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicRedactedThinkingBlock>(null, AnthropicRedactedThinkingBlock);
            }
            else if(AnthropicServerToolUseBlock != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicServerToolUseBlock>(null, AnthropicServerToolUseBlock);
            }
            else if(AnthropicTextBlock != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicTextBlock>(null, AnthropicTextBlock);
            }
            else if(AnthropicTextEditorCodeExecutionToolResult != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicTextEditorCodeExecutionToolResult>(null, AnthropicTextEditorCodeExecutionToolResult);
            }
            else if(AnthropicThinkingBlock != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicThinkingBlock>(null, AnthropicThinkingBlock);
            }
            else if(AnthropicToolSearchToolResult != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicToolSearchToolResult>(null, AnthropicToolSearchToolResult);
            }
            else if(AnthropicToolUseBlock != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicToolUseBlock>(null, AnthropicToolUseBlock);
            }
            else if(AnthropicWebFetchToolResult != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicWebFetchToolResult>(null, AnthropicWebFetchToolResult);
            }
            else if(AnthropicWebSearchToolResult != null)
            {
                writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.AnthropicWebSearchToolResult>(null, AnthropicWebSearchToolResult);
            }
        }
    }
}
#pragma warning restore CS0618
