// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum OutputFileSearchServerToolItem_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "openrouter:file_search")]
        #pragma warning disable CS1591
        OpenrouterFile_search,
        #pragma warning restore CS1591
    }
}
