// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class OutputItemReasoning : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The content property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenRouter.OpenApiClient.Models.ReasoningTextContent>? Content { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenRouter.OpenApiClient.Models.ReasoningTextContent> Content { get; set; }
#endif
        /// <summary>The encrypted_content property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EncryptedContent { get; set; }
#nullable restore
#else
        public string EncryptedContent { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.OutputItemReasoning.OutputItemReasoning_status? Status { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.OutputItemReasoning.OutputItemReasoning_status Status { get; set; }
#endif
        /// <summary>The summary property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenRouter.OpenApiClient.Models.ReasoningSummaryText>? Summary { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenRouter.OpenApiClient.Models.ReasoningSummaryText> Summary { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.OpenRouter.OpenApiClient.Models.OutputItemReasoning_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.OutputItemReasoning"/> and sets the default values.
        /// </summary>
        public OutputItemReasoning()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.OutputItemReasoning"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenRouter.OpenApiClient.Models.OutputItemReasoning CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenRouter.OpenApiClient.Models.OutputItemReasoning();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "content", n => { Content = n.GetCollectionOfObjectValues<global::Soenneker.OpenRouter.OpenApiClient.Models.ReasoningTextContent>(global::Soenneker.OpenRouter.OpenApiClient.Models.ReasoningTextContent.CreateFromDiscriminatorValue)?.AsList(); } },
                { "encrypted_content", n => { EncryptedContent = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "status", n => { Status = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.OutputItemReasoning.OutputItemReasoning_status>(global::Soenneker.OpenRouter.OpenApiClient.Models.OutputItemReasoning.OutputItemReasoning_status.CreateFromDiscriminatorValue); } },
                { "summary", n => { Summary = n.GetCollectionOfObjectValues<global::Soenneker.OpenRouter.OpenApiClient.Models.ReasoningSummaryText>(global::Soenneker.OpenRouter.OpenApiClient.Models.ReasoningSummaryText.CreateFromDiscriminatorValue)?.AsList(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.OutputItemReasoning_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenRouter.OpenApiClient.Models.ReasoningTextContent>("content", Content);
            writer.WriteStringValue("encrypted_content", EncryptedContent);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.OutputItemReasoning.OutputItemReasoning_status>("status", Status);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenRouter.OpenApiClient.Models.ReasoningSummaryText>("summary", Summary);
            writer.WriteEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.OutputItemReasoning_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class OutputItemReasoning_status : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.OutputItemReasoning.OutputItemReasoning_status"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.OpenRouter.OpenApiClient.Models.OutputItemReasoning.OutputItemReasoning_status CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.OpenRouter.OpenApiClient.Models.OutputItemReasoning.OutputItemReasoning_status();
                if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
            }
        }
    }
}
#pragma warning restore CS0618
