// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum OutputCustomToolCallItem_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "custom_tool_call")]
        #pragma warning disable CS1591
        Custom_tool_call,
        #pragma warning restore CS1591
    }
}
