// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    /// <summary>
    /// An openrouter:fusion server tool output item
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OutputFusionServerToolItem : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Structured analysis produced by the fusion judge model.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.OutputFusionServerToolItem_analysis? Analysis { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.OutputFusionServerToolItem_analysis Analysis { get; set; }
#endif
        /// <summary>Error message when the fusion run did not produce an analysis result.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Error { get; set; }
#nullable restore
#else
        public string Error { get; set; }
#endif
        /// <summary>Models that were requested as part of the analysis panel but did not produce a response. Present when at least one requested analysis model failed. The fusion result is still usable but was produced from a degraded panel.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenRouter.OpenApiClient.Models.OutputFusionServerToolItem_failed_models>? FailedModels { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenRouter.OpenApiClient.Models.OutputFusionServerToolItem_failed_models> FailedModels { get; set; }
#endif
        /// <summary>Typed failure reason when the fusion run failed. Possible values include: all_panels_failed, insufficient_credits, rate_limited, judge_not_valid_json, judge_schema_mismatch, judge_upstream_error, judge_empty_completion.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FailureReason { get; set; }
#nullable restore
#else
        public string FailureReason { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Slugs of the analysis models that produced a response in this fusion run.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenRouter.OpenApiClient.Models.OutputFusionServerToolItem_responses>? Responses { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenRouter.OpenApiClient.Models.OutputFusionServerToolItem_responses> Responses { get; set; }
#endif
        /// <summary>The status property</summary>
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ToolCallStatus? Status { get; set; }
        /// <summary>The type property</summary>
        public global::Soenneker.OpenRouter.OpenApiClient.Models.OutputFusionServerToolItem_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.OutputFusionServerToolItem"/> and sets the default values.
        /// </summary>
        public OutputFusionServerToolItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.OutputFusionServerToolItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenRouter.OpenApiClient.Models.OutputFusionServerToolItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenRouter.OpenApiClient.Models.OutputFusionServerToolItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "analysis", n => { Analysis = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.OutputFusionServerToolItem_analysis>(global::Soenneker.OpenRouter.OpenApiClient.Models.OutputFusionServerToolItem_analysis.CreateFromDiscriminatorValue); } },
                { "error", n => { Error = n.GetStringValue(); } },
                { "failed_models", n => { FailedModels = n.GetCollectionOfObjectValues<global::Soenneker.OpenRouter.OpenApiClient.Models.OutputFusionServerToolItem_failed_models>(global::Soenneker.OpenRouter.OpenApiClient.Models.OutputFusionServerToolItem_failed_models.CreateFromDiscriminatorValue)?.AsList(); } },
                { "failure_reason", n => { FailureReason = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "responses", n => { Responses = n.GetCollectionOfObjectValues<global::Soenneker.OpenRouter.OpenApiClient.Models.OutputFusionServerToolItem_responses>(global::Soenneker.OpenRouter.OpenApiClient.Models.OutputFusionServerToolItem_responses.CreateFromDiscriminatorValue)?.AsList(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ToolCallStatus>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.OutputFusionServerToolItem_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.OutputFusionServerToolItem_analysis>("analysis", Analysis);
            writer.WriteStringValue("error", Error);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenRouter.OpenApiClient.Models.OutputFusionServerToolItem_failed_models>("failed_models", FailedModels);
            writer.WriteStringValue("failure_reason", FailureReason);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenRouter.OpenApiClient.Models.OutputFusionServerToolItem_responses>("responses", Responses);
            writer.WriteEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ToolCallStatus>("status", Status);
            writer.WriteEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.OutputFusionServerToolItem_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
