// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Parameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "temperature")]
        #pragma warning disable CS1591
        Temperature,
        #pragma warning restore CS1591
        [EnumMember(Value = "top_p")]
        #pragma warning disable CS1591
        Top_p,
        #pragma warning restore CS1591
        [EnumMember(Value = "top_k")]
        #pragma warning disable CS1591
        Top_k,
        #pragma warning restore CS1591
        [EnumMember(Value = "min_p")]
        #pragma warning disable CS1591
        Min_p,
        #pragma warning restore CS1591
        [EnumMember(Value = "top_a")]
        #pragma warning disable CS1591
        Top_a,
        #pragma warning restore CS1591
        [EnumMember(Value = "frequency_penalty")]
        #pragma warning disable CS1591
        Frequency_penalty,
        #pragma warning restore CS1591
        [EnumMember(Value = "presence_penalty")]
        #pragma warning disable CS1591
        Presence_penalty,
        #pragma warning restore CS1591
        [EnumMember(Value = "repetition_penalty")]
        #pragma warning disable CS1591
        Repetition_penalty,
        #pragma warning restore CS1591
        [EnumMember(Value = "max_tokens")]
        #pragma warning disable CS1591
        Max_tokens,
        #pragma warning restore CS1591
        [EnumMember(Value = "logit_bias")]
        #pragma warning disable CS1591
        Logit_bias,
        #pragma warning restore CS1591
        [EnumMember(Value = "logprobs")]
        #pragma warning disable CS1591
        Logprobs,
        #pragma warning restore CS1591
        [EnumMember(Value = "top_logprobs")]
        #pragma warning disable CS1591
        Top_logprobs,
        #pragma warning restore CS1591
        [EnumMember(Value = "seed")]
        #pragma warning disable CS1591
        Seed,
        #pragma warning restore CS1591
        [EnumMember(Value = "response_format")]
        #pragma warning disable CS1591
        Response_format,
        #pragma warning restore CS1591
        [EnumMember(Value = "structured_outputs")]
        #pragma warning disable CS1591
        Structured_outputs,
        #pragma warning restore CS1591
        [EnumMember(Value = "stop")]
        #pragma warning disable CS1591
        Stop,
        #pragma warning restore CS1591
        [EnumMember(Value = "tools")]
        #pragma warning disable CS1591
        Tools,
        #pragma warning restore CS1591
        [EnumMember(Value = "tool_choice")]
        #pragma warning disable CS1591
        Tool_choice,
        #pragma warning restore CS1591
        [EnumMember(Value = "parallel_tool_calls")]
        #pragma warning disable CS1591
        Parallel_tool_calls,
        #pragma warning restore CS1591
        [EnumMember(Value = "include_reasoning")]
        #pragma warning disable CS1591
        Include_reasoning,
        #pragma warning restore CS1591
        [EnumMember(Value = "reasoning")]
        #pragma warning disable CS1591
        Reasoning,
        #pragma warning restore CS1591
        [EnumMember(Value = "reasoning_effort")]
        #pragma warning disable CS1591
        Reasoning_effort,
        #pragma warning restore CS1591
        [EnumMember(Value = "web_search_options")]
        #pragma warning disable CS1591
        Web_search_options,
        #pragma warning restore CS1591
        [EnumMember(Value = "verbosity")]
        #pragma warning disable CS1591
        Verbosity,
        #pragma warning restore CS1591
    }
}
