// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum PDFParserEngine_Wrapper_value
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "mistral-ocr")]
        #pragma warning disable CS1591
        MistralOcr,
        #pragma warning restore CS1591
        [EnumMember(Value = "native")]
        #pragma warning disable CS1591
        Native,
        #pragma warning restore CS1591
        [EnumMember(Value = "cloudflare-ai")]
        #pragma warning disable CS1591
        CloudflareAi,
        #pragma warning restore CS1591
    }
}
