// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    /// <summary>Categorical kind of a pipeline stage. Multiple plugins can share a type (e.g. all guardrail-level plugins emit `guardrail`); the `name` field disambiguates which plugin emitted it.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PipelineStageType
    {
        [EnumMember(Value = "router")]
        #pragma warning disable CS1591
        Router,
        #pragma warning restore CS1591
        [EnumMember(Value = "guardrail")]
        #pragma warning disable CS1591
        Guardrail,
        #pragma warning restore CS1591
        [EnumMember(Value = "web_search")]
        #pragma warning disable CS1591
        Web_search,
        #pragma warning restore CS1591
        [EnumMember(Value = "file_parser")]
        #pragma warning disable CS1591
        File_parser,
        #pragma warning restore CS1591
        [EnumMember(Value = "server_tools")]
        #pragma warning disable CS1591
        Server_tools,
        #pragma warning restore CS1591
        [EnumMember(Value = "response_healing")]
        #pragma warning disable CS1591
        Response_healing,
        #pragma warning restore CS1591
        [EnumMember(Value = "context_compression")]
        #pragma warning disable CS1591
        Context_compression,
        #pragma warning restore CS1591
    }
}
