// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    /// <summary>
    /// Details of a provider response for a generation attempt
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProviderResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Internal endpoint identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EndpointId { get; set; }
#nullable restore
#else
        public string EndpointId { get; set; }
#endif
        /// <summary>Upstream provider response identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Whether the request used a bring-your-own-key</summary>
        public bool? IsByok { get; set; }
        /// <summary>Response latency in milliseconds</summary>
        public double? Latency { get; set; }
        /// <summary>Canonical model slug</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ModelPermaslug { get; set; }
#nullable restore
#else
        public string ModelPermaslug { get; set; }
#endif
        /// <summary>Name of the provider</summary>
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderResponse_provider_name? ProviderName { get; set; }
        /// <summary>HTTP status code from the provider</summary>
        public double? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderResponse"/> and sets the default values.
        /// </summary>
        public ProviderResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "endpoint_id", n => { EndpointId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "is_byok", n => { IsByok = n.GetBoolValue(); } },
                { "latency", n => { Latency = n.GetDoubleValue(); } },
                { "model_permaslug", n => { ModelPermaslug = n.GetStringValue(); } },
                { "provider_name", n => { ProviderName = n.GetEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderResponse_provider_name>(); } },
                { "status", n => { Status = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("endpoint_id", EndpointId);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("is_byok", IsByok);
            writer.WriteDoubleValue("latency", Latency);
            writer.WriteStringValue("model_permaslug", ModelPermaslug);
            writer.WriteEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderResponse_provider_name>("provider_name", ProviderName);
            writer.WriteDoubleValue("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
