// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    /// <summary>
    /// Provider-specific options keyed by provider slug. The options for the matched provider are spread into the upstream request body.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProviderOptions : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ai21 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ai21? Ai21 { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ai21 Ai21 { get; set; }
#endif
        /// <summary>The aionLabs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_aionLabs? AionLabs { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_aionLabs AionLabs { get; set; }
#endif
        /// <summary>The akashml property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_akashml? Akashml { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_akashml Akashml { get; set; }
#endif
        /// <summary>The alibaba property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_alibaba? Alibaba { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_alibaba Alibaba { get; set; }
#endif
        /// <summary>The amazonBedrock property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_amazonBedrock? AmazonBedrock { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_amazonBedrock AmazonBedrock { get; set; }
#endif
        /// <summary>The amazonNova property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_amazonNova? AmazonNova { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_amazonNova AmazonNova { get; set; }
#endif
        /// <summary>The ambient property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ambient? Ambient { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ambient Ambient { get; set; }
#endif
        /// <summary>The anthropic property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_anthropic? Anthropic { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_anthropic Anthropic { get; set; }
#endif
        /// <summary>The anyscale property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_anyscale? Anyscale { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_anyscale Anyscale { get; set; }
#endif
        /// <summary>The arceeAi property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_arceeAi? ArceeAi { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_arceeAi ArceeAi { get; set; }
#endif
        /// <summary>The atlasCloud property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_atlasCloud? AtlasCloud { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_atlasCloud AtlasCloud { get; set; }
#endif
        /// <summary>The atoma property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_atoma? Atoma { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_atoma Atoma { get; set; }
#endif
        /// <summary>The avian property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_avian? Avian { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_avian Avian { get; set; }
#endif
        /// <summary>The azure property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_azure? Azure { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_azure Azure { get; set; }
#endif
        /// <summary>The baidu property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_baidu? Baidu { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_baidu Baidu { get; set; }
#endif
        /// <summary>The baseten property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_baseten? Baseten { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_baseten Baseten { get; set; }
#endif
        /// <summary>The blackForestLabs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_blackForestLabs? BlackForestLabs { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_blackForestLabs BlackForestLabs { get; set; }
#endif
        /// <summary>The byteplus property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_byteplus? Byteplus { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_byteplus Byteplus { get; set; }
#endif
        /// <summary>The centml property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_centml? Centml { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_centml Centml { get; set; }
#endif
        /// <summary>The cerebras property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_cerebras? Cerebras { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_cerebras Cerebras { get; set; }
#endif
        /// <summary>The chutes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_chutes? Chutes { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_chutes Chutes { get; set; }
#endif
        /// <summary>The cirrascale property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_cirrascale? Cirrascale { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_cirrascale Cirrascale { get; set; }
#endif
        /// <summary>The clarifai property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_clarifai? Clarifai { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_clarifai Clarifai { get; set; }
#endif
        /// <summary>The cloudflare property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_cloudflare? Cloudflare { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_cloudflare Cloudflare { get; set; }
#endif
        /// <summary>The cohere property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_cohere? Cohere { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_cohere Cohere { get; set; }
#endif
        /// <summary>The crofai property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_crofai? Crofai { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_crofai Crofai { get; set; }
#endif
        /// <summary>The crusoe property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_crusoe? Crusoe { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_crusoe Crusoe { get; set; }
#endif
        /// <summary>The deepinfra property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_deepinfra? Deepinfra { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_deepinfra Deepinfra { get; set; }
#endif
        /// <summary>The deepseek property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_deepseek? Deepseek { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_deepseek Deepseek { get; set; }
#endif
        /// <summary>The dekallm property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_dekallm? Dekallm { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_dekallm Dekallm { get; set; }
#endif
        /// <summary>The enfer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_enfer? Enfer { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_enfer Enfer { get; set; }
#endif
        /// <summary>The fakeProvider property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_fakeProvider? FakeProvider { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_fakeProvider FakeProvider { get; set; }
#endif
        /// <summary>The featherless property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_featherless? Featherless { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_featherless Featherless { get; set; }
#endif
        /// <summary>The fireworks property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_fireworks? Fireworks { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_fireworks Fireworks { get; set; }
#endif
        /// <summary>The friendli property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_friendli? Friendli { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_friendli Friendli { get; set; }
#endif
        /// <summary>The gmicloud property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_gmicloud? Gmicloud { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_gmicloud Gmicloud { get; set; }
#endif
        /// <summary>The googleAiStudio property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_googleAiStudio? GoogleAiStudio { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_googleAiStudio GoogleAiStudio { get; set; }
#endif
        /// <summary>The googleVertex property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_googleVertex? GoogleVertex { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_googleVertex GoogleVertex { get; set; }
#endif
        /// <summary>The gopomelo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_gopomelo? Gopomelo { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_gopomelo Gopomelo { get; set; }
#endif
        /// <summary>The groq property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_groq? Groq { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_groq Groq { get; set; }
#endif
        /// <summary>The huggingface property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_huggingface? Huggingface { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_huggingface Huggingface { get; set; }
#endif
        /// <summary>The hyperbolic property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_hyperbolic? Hyperbolic { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_hyperbolic Hyperbolic { get; set; }
#endif
        /// <summary>The hyperbolicQuantized property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_hyperbolicQuantized? HyperbolicQuantized { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_hyperbolicQuantized HyperbolicQuantized { get; set; }
#endif
        /// <summary>The inception property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_inception? Inception { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_inception Inception { get; set; }
#endif
        /// <summary>The inceptron property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_inceptron? Inceptron { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_inceptron Inceptron { get; set; }
#endif
        /// <summary>The inferenceNet property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_inferenceNet? InferenceNet { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_inferenceNet InferenceNet { get; set; }
#endif
        /// <summary>The infermatic property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_infermatic? Infermatic { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_infermatic Infermatic { get; set; }
#endif
        /// <summary>The inflection property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_inflection? Inflection { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_inflection Inflection { get; set; }
#endif
        /// <summary>The inocloud property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_inocloud? Inocloud { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_inocloud Inocloud { get; set; }
#endif
        /// <summary>The ioNet property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ioNet? IoNet { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ioNet IoNet { get; set; }
#endif
        /// <summary>The ionstream property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ionstream? Ionstream { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ionstream Ionstream { get; set; }
#endif
        /// <summary>The klusterai property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_klusterai? Klusterai { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_klusterai Klusterai { get; set; }
#endif
        /// <summary>The lambda property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_lambda? Lambda { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_lambda Lambda { get; set; }
#endif
        /// <summary>The lepton property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_lepton? Lepton { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_lepton Lepton { get; set; }
#endif
        /// <summary>The liquid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_liquid? Liquid { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_liquid Liquid { get; set; }
#endif
        /// <summary>The lynn property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_lynn? Lynn { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_lynn Lynn { get; set; }
#endif
        /// <summary>The lynnPrivate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_lynnPrivate? LynnPrivate { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_lynnPrivate LynnPrivate { get; set; }
#endif
        /// <summary>The mancer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_mancer? Mancer { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_mancer Mancer { get; set; }
#endif
        /// <summary>The mancerOld property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_mancerOld? MancerOld { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_mancerOld MancerOld { get; set; }
#endif
        /// <summary>The mara property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_mara? Mara { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_mara Mara { get; set; }
#endif
        /// <summary>The meta property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_meta? Meta { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_meta Meta { get; set; }
#endif
        /// <summary>The minimax property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_minimax? Minimax { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_minimax Minimax { get; set; }
#endif
        /// <summary>The mistral property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_mistral? Mistral { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_mistral Mistral { get; set; }
#endif
        /// <summary>The modal property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_modal? Modal { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_modal Modal { get; set; }
#endif
        /// <summary>The modelrun property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_modelrun? Modelrun { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_modelrun Modelrun { get; set; }
#endif
        /// <summary>The modular property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_modular? Modular { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_modular Modular { get; set; }
#endif
        /// <summary>The moonshotai property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_moonshotai? Moonshotai { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_moonshotai Moonshotai { get; set; }
#endif
        /// <summary>The morph property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_morph? Morph { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_morph Morph { get; set; }
#endif
        /// <summary>The ncompass property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ncompass? Ncompass { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ncompass Ncompass { get; set; }
#endif
        /// <summary>The nebius property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_nebius? Nebius { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_nebius Nebius { get; set; }
#endif
        /// <summary>The nexAgi property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_nexAgi? NexAgi { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_nexAgi NexAgi { get; set; }
#endif
        /// <summary>The nextbit property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_nextbit? Nextbit { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_nextbit Nextbit { get; set; }
#endif
        /// <summary>The nineteen property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_nineteen? Nineteen { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_nineteen Nineteen { get; set; }
#endif
        /// <summary>The novita property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_novita? Novita { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_novita Novita { get; set; }
#endif
        /// <summary>The nvidia property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_nvidia? Nvidia { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_nvidia Nvidia { get; set; }
#endif
        /// <summary>The octoai property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_octoai? Octoai { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_octoai Octoai { get; set; }
#endif
        /// <summary>The openai property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_openai? Openai { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_openai Openai { get; set; }
#endif
        /// <summary>The openInference property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_openInference? OpenInference { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_openInference OpenInference { get; set; }
#endif
        /// <summary>The parasail property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_parasail? Parasail { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_parasail Parasail { get; set; }
#endif
        /// <summary>The perplexity property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_perplexity? Perplexity { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_perplexity Perplexity { get; set; }
#endif
        /// <summary>The phala property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_phala? Phala { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_phala Phala { get; set; }
#endif
        /// <summary>The poolside property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_poolside? Poolside { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_poolside Poolside { get; set; }
#endif
        /// <summary>The recraft property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_recraft? Recraft { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_recraft Recraft { get; set; }
#endif
        /// <summary>The recursal property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_recursal? Recursal { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_recursal Recursal { get; set; }
#endif
        /// <summary>The reflection property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_reflection? Reflection { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_reflection Reflection { get; set; }
#endif
        /// <summary>The reka property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_reka? Reka { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_reka Reka { get; set; }
#endif
        /// <summary>The relace property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_relace? Relace { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_relace Relace { get; set; }
#endif
        /// <summary>The replicate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_replicate? Replicate { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_replicate Replicate { get; set; }
#endif
        /// <summary>The sambanova property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_sambanova? Sambanova { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_sambanova Sambanova { get; set; }
#endif
        /// <summary>The sambanovaCloaked property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_sambanovaCloaked? SambanovaCloaked { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_sambanovaCloaked SambanovaCloaked { get; set; }
#endif
        /// <summary>The seed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_seed? Seed { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_seed Seed { get; set; }
#endif
        /// <summary>The sfCompute property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_sfCompute? SfCompute { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_sfCompute SfCompute { get; set; }
#endif
        /// <summary>The siliconflow property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_siliconflow? Siliconflow { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_siliconflow Siliconflow { get; set; }
#endif
        /// <summary>The sourceful property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_sourceful? Sourceful { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_sourceful Sourceful { get; set; }
#endif
        /// <summary>The stealth property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_stealth? Stealth { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_stealth Stealth { get; set; }
#endif
        /// <summary>The stepfun property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_stepfun? Stepfun { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_stepfun Stepfun { get; set; }
#endif
        /// <summary>The streamlake property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_streamlake? Streamlake { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_streamlake Streamlake { get; set; }
#endif
        /// <summary>The switchpoint property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_switchpoint? Switchpoint { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_switchpoint Switchpoint { get; set; }
#endif
        /// <summary>The targon property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_targon? Targon { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_targon Targon { get; set; }
#endif
        /// <summary>The together property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_together? Together { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_together Together { get; set; }
#endif
        /// <summary>The togetherLite property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_togetherLite? TogetherLite { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_togetherLite TogetherLite { get; set; }
#endif
        /// <summary>The ubicloud property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ubicloud? Ubicloud { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ubicloud Ubicloud { get; set; }
#endif
        /// <summary>The upstage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_upstage? Upstage { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_upstage Upstage { get; set; }
#endif
        /// <summary>The venice property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_venice? Venice { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_venice Venice { get; set; }
#endif
        /// <summary>The wandb property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_wandb? Wandb { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_wandb Wandb { get; set; }
#endif
        /// <summary>The xai property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_xai? Xai { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_xai Xai { get; set; }
#endif
        /// <summary>The xiaomi property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_xiaomi? Xiaomi { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_xiaomi Xiaomi { get; set; }
#endif
        /// <summary>The zAi property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_zAi? ZAi { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_zAi ZAi { get; set; }
#endif
        /// <summary>The ZeroOneai property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ZeroOneai? ZeroOneai { get; set; }
#nullable restore
#else
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ZeroOneai ZeroOneai { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions"/> and sets the default values.
        /// </summary>
        public ProviderOptions()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ai21", n => { Ai21 = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ai21>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ai21.CreateFromDiscriminatorValue); } },
                { "aion-labs", n => { AionLabs = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_aionLabs>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_aionLabs.CreateFromDiscriminatorValue); } },
                { "akashml", n => { Akashml = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_akashml>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_akashml.CreateFromDiscriminatorValue); } },
                { "alibaba", n => { Alibaba = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_alibaba>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_alibaba.CreateFromDiscriminatorValue); } },
                { "amazon-bedrock", n => { AmazonBedrock = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_amazonBedrock>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_amazonBedrock.CreateFromDiscriminatorValue); } },
                { "amazon-nova", n => { AmazonNova = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_amazonNova>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_amazonNova.CreateFromDiscriminatorValue); } },
                { "ambient", n => { Ambient = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ambient>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ambient.CreateFromDiscriminatorValue); } },
                { "anthropic", n => { Anthropic = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_anthropic>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_anthropic.CreateFromDiscriminatorValue); } },
                { "anyscale", n => { Anyscale = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_anyscale>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_anyscale.CreateFromDiscriminatorValue); } },
                { "arcee-ai", n => { ArceeAi = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_arceeAi>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_arceeAi.CreateFromDiscriminatorValue); } },
                { "atlas-cloud", n => { AtlasCloud = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_atlasCloud>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_atlasCloud.CreateFromDiscriminatorValue); } },
                { "atoma", n => { Atoma = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_atoma>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_atoma.CreateFromDiscriminatorValue); } },
                { "avian", n => { Avian = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_avian>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_avian.CreateFromDiscriminatorValue); } },
                { "azure", n => { Azure = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_azure>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_azure.CreateFromDiscriminatorValue); } },
                { "baidu", n => { Baidu = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_baidu>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_baidu.CreateFromDiscriminatorValue); } },
                { "baseten", n => { Baseten = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_baseten>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_baseten.CreateFromDiscriminatorValue); } },
                { "black-forest-labs", n => { BlackForestLabs = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_blackForestLabs>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_blackForestLabs.CreateFromDiscriminatorValue); } },
                { "byteplus", n => { Byteplus = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_byteplus>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_byteplus.CreateFromDiscriminatorValue); } },
                { "centml", n => { Centml = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_centml>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_centml.CreateFromDiscriminatorValue); } },
                { "cerebras", n => { Cerebras = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_cerebras>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_cerebras.CreateFromDiscriminatorValue); } },
                { "chutes", n => { Chutes = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_chutes>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_chutes.CreateFromDiscriminatorValue); } },
                { "cirrascale", n => { Cirrascale = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_cirrascale>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_cirrascale.CreateFromDiscriminatorValue); } },
                { "clarifai", n => { Clarifai = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_clarifai>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_clarifai.CreateFromDiscriminatorValue); } },
                { "cloudflare", n => { Cloudflare = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_cloudflare>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_cloudflare.CreateFromDiscriminatorValue); } },
                { "cohere", n => { Cohere = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_cohere>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_cohere.CreateFromDiscriminatorValue); } },
                { "crofai", n => { Crofai = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_crofai>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_crofai.CreateFromDiscriminatorValue); } },
                { "crusoe", n => { Crusoe = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_crusoe>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_crusoe.CreateFromDiscriminatorValue); } },
                { "deepinfra", n => { Deepinfra = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_deepinfra>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_deepinfra.CreateFromDiscriminatorValue); } },
                { "deepseek", n => { Deepseek = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_deepseek>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_deepseek.CreateFromDiscriminatorValue); } },
                { "dekallm", n => { Dekallm = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_dekallm>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_dekallm.CreateFromDiscriminatorValue); } },
                { "enfer", n => { Enfer = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_enfer>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_enfer.CreateFromDiscriminatorValue); } },
                { "fake-provider", n => { FakeProvider = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_fakeProvider>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_fakeProvider.CreateFromDiscriminatorValue); } },
                { "featherless", n => { Featherless = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_featherless>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_featherless.CreateFromDiscriminatorValue); } },
                { "fireworks", n => { Fireworks = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_fireworks>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_fireworks.CreateFromDiscriminatorValue); } },
                { "friendli", n => { Friendli = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_friendli>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_friendli.CreateFromDiscriminatorValue); } },
                { "gmicloud", n => { Gmicloud = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_gmicloud>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_gmicloud.CreateFromDiscriminatorValue); } },
                { "google-ai-studio", n => { GoogleAiStudio = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_googleAiStudio>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_googleAiStudio.CreateFromDiscriminatorValue); } },
                { "google-vertex", n => { GoogleVertex = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_googleVertex>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_googleVertex.CreateFromDiscriminatorValue); } },
                { "gopomelo", n => { Gopomelo = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_gopomelo>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_gopomelo.CreateFromDiscriminatorValue); } },
                { "groq", n => { Groq = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_groq>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_groq.CreateFromDiscriminatorValue); } },
                { "huggingface", n => { Huggingface = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_huggingface>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_huggingface.CreateFromDiscriminatorValue); } },
                { "hyperbolic", n => { Hyperbolic = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_hyperbolic>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_hyperbolic.CreateFromDiscriminatorValue); } },
                { "hyperbolic-quantized", n => { HyperbolicQuantized = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_hyperbolicQuantized>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_hyperbolicQuantized.CreateFromDiscriminatorValue); } },
                { "inception", n => { Inception = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_inception>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_inception.CreateFromDiscriminatorValue); } },
                { "inceptron", n => { Inceptron = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_inceptron>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_inceptron.CreateFromDiscriminatorValue); } },
                { "inference-net", n => { InferenceNet = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_inferenceNet>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_inferenceNet.CreateFromDiscriminatorValue); } },
                { "infermatic", n => { Infermatic = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_infermatic>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_infermatic.CreateFromDiscriminatorValue); } },
                { "inflection", n => { Inflection = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_inflection>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_inflection.CreateFromDiscriminatorValue); } },
                { "inocloud", n => { Inocloud = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_inocloud>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_inocloud.CreateFromDiscriminatorValue); } },
                { "io-net", n => { IoNet = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ioNet>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ioNet.CreateFromDiscriminatorValue); } },
                { "ionstream", n => { Ionstream = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ionstream>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ionstream.CreateFromDiscriminatorValue); } },
                { "klusterai", n => { Klusterai = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_klusterai>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_klusterai.CreateFromDiscriminatorValue); } },
                { "lambda", n => { Lambda = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_lambda>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_lambda.CreateFromDiscriminatorValue); } },
                { "lepton", n => { Lepton = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_lepton>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_lepton.CreateFromDiscriminatorValue); } },
                { "liquid", n => { Liquid = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_liquid>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_liquid.CreateFromDiscriminatorValue); } },
                { "lynn", n => { Lynn = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_lynn>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_lynn.CreateFromDiscriminatorValue); } },
                { "lynn-private", n => { LynnPrivate = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_lynnPrivate>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_lynnPrivate.CreateFromDiscriminatorValue); } },
                { "mancer", n => { Mancer = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_mancer>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_mancer.CreateFromDiscriminatorValue); } },
                { "mancer-old", n => { MancerOld = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_mancerOld>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_mancerOld.CreateFromDiscriminatorValue); } },
                { "mara", n => { Mara = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_mara>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_mara.CreateFromDiscriminatorValue); } },
                { "meta", n => { Meta = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_meta>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_meta.CreateFromDiscriminatorValue); } },
                { "minimax", n => { Minimax = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_minimax>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_minimax.CreateFromDiscriminatorValue); } },
                { "mistral", n => { Mistral = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_mistral>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_mistral.CreateFromDiscriminatorValue); } },
                { "modal", n => { Modal = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_modal>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_modal.CreateFromDiscriminatorValue); } },
                { "modelrun", n => { Modelrun = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_modelrun>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_modelrun.CreateFromDiscriminatorValue); } },
                { "modular", n => { Modular = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_modular>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_modular.CreateFromDiscriminatorValue); } },
                { "moonshotai", n => { Moonshotai = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_moonshotai>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_moonshotai.CreateFromDiscriminatorValue); } },
                { "morph", n => { Morph = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_morph>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_morph.CreateFromDiscriminatorValue); } },
                { "ncompass", n => { Ncompass = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ncompass>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ncompass.CreateFromDiscriminatorValue); } },
                { "nebius", n => { Nebius = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_nebius>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_nebius.CreateFromDiscriminatorValue); } },
                { "nex-agi", n => { NexAgi = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_nexAgi>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_nexAgi.CreateFromDiscriminatorValue); } },
                { "nextbit", n => { Nextbit = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_nextbit>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_nextbit.CreateFromDiscriminatorValue); } },
                { "nineteen", n => { Nineteen = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_nineteen>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_nineteen.CreateFromDiscriminatorValue); } },
                { "novita", n => { Novita = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_novita>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_novita.CreateFromDiscriminatorValue); } },
                { "nvidia", n => { Nvidia = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_nvidia>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_nvidia.CreateFromDiscriminatorValue); } },
                { "octoai", n => { Octoai = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_octoai>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_octoai.CreateFromDiscriminatorValue); } },
                { "open-inference", n => { OpenInference = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_openInference>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_openInference.CreateFromDiscriminatorValue); } },
                { "openai", n => { Openai = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_openai>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_openai.CreateFromDiscriminatorValue); } },
                { "parasail", n => { Parasail = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_parasail>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_parasail.CreateFromDiscriminatorValue); } },
                { "perplexity", n => { Perplexity = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_perplexity>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_perplexity.CreateFromDiscriminatorValue); } },
                { "phala", n => { Phala = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_phala>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_phala.CreateFromDiscriminatorValue); } },
                { "poolside", n => { Poolside = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_poolside>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_poolside.CreateFromDiscriminatorValue); } },
                { "recraft", n => { Recraft = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_recraft>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_recraft.CreateFromDiscriminatorValue); } },
                { "recursal", n => { Recursal = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_recursal>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_recursal.CreateFromDiscriminatorValue); } },
                { "reflection", n => { Reflection = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_reflection>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_reflection.CreateFromDiscriminatorValue); } },
                { "reka", n => { Reka = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_reka>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_reka.CreateFromDiscriminatorValue); } },
                { "relace", n => { Relace = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_relace>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_relace.CreateFromDiscriminatorValue); } },
                { "replicate", n => { Replicate = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_replicate>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_replicate.CreateFromDiscriminatorValue); } },
                { "sambanova", n => { Sambanova = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_sambanova>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_sambanova.CreateFromDiscriminatorValue); } },
                { "sambanova-cloaked", n => { SambanovaCloaked = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_sambanovaCloaked>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_sambanovaCloaked.CreateFromDiscriminatorValue); } },
                { "seed", n => { Seed = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_seed>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_seed.CreateFromDiscriminatorValue); } },
                { "sf-compute", n => { SfCompute = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_sfCompute>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_sfCompute.CreateFromDiscriminatorValue); } },
                { "siliconflow", n => { Siliconflow = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_siliconflow>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_siliconflow.CreateFromDiscriminatorValue); } },
                { "sourceful", n => { Sourceful = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_sourceful>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_sourceful.CreateFromDiscriminatorValue); } },
                { "stealth", n => { Stealth = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_stealth>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_stealth.CreateFromDiscriminatorValue); } },
                { "stepfun", n => { Stepfun = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_stepfun>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_stepfun.CreateFromDiscriminatorValue); } },
                { "streamlake", n => { Streamlake = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_streamlake>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_streamlake.CreateFromDiscriminatorValue); } },
                { "switchpoint", n => { Switchpoint = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_switchpoint>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_switchpoint.CreateFromDiscriminatorValue); } },
                { "targon", n => { Targon = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_targon>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_targon.CreateFromDiscriminatorValue); } },
                { "together", n => { Together = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_together>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_together.CreateFromDiscriminatorValue); } },
                { "together-lite", n => { TogetherLite = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_togetherLite>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_togetherLite.CreateFromDiscriminatorValue); } },
                { "ubicloud", n => { Ubicloud = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ubicloud>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ubicloud.CreateFromDiscriminatorValue); } },
                { "upstage", n => { Upstage = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_upstage>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_upstage.CreateFromDiscriminatorValue); } },
                { "venice", n => { Venice = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_venice>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_venice.CreateFromDiscriminatorValue); } },
                { "wandb", n => { Wandb = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_wandb>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_wandb.CreateFromDiscriminatorValue); } },
                { "xai", n => { Xai = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_xai>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_xai.CreateFromDiscriminatorValue); } },
                { "xiaomi", n => { Xiaomi = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_xiaomi>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_xiaomi.CreateFromDiscriminatorValue); } },
                { "z-ai", n => { ZAi = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_zAi>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_zAi.CreateFromDiscriminatorValue); } },
                { "01ai", n => { ZeroOneai = n.GetObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ZeroOneai>(global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ZeroOneai.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ai21>("ai21", Ai21);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_aionLabs>("aion-labs", AionLabs);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_akashml>("akashml", Akashml);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_alibaba>("alibaba", Alibaba);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_amazonBedrock>("amazon-bedrock", AmazonBedrock);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_amazonNova>("amazon-nova", AmazonNova);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ambient>("ambient", Ambient);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_anthropic>("anthropic", Anthropic);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_anyscale>("anyscale", Anyscale);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_arceeAi>("arcee-ai", ArceeAi);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_atlasCloud>("atlas-cloud", AtlasCloud);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_atoma>("atoma", Atoma);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_avian>("avian", Avian);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_azure>("azure", Azure);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_baidu>("baidu", Baidu);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_baseten>("baseten", Baseten);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_blackForestLabs>("black-forest-labs", BlackForestLabs);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_byteplus>("byteplus", Byteplus);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_centml>("centml", Centml);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_cerebras>("cerebras", Cerebras);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_chutes>("chutes", Chutes);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_cirrascale>("cirrascale", Cirrascale);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_clarifai>("clarifai", Clarifai);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_cloudflare>("cloudflare", Cloudflare);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_cohere>("cohere", Cohere);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_crofai>("crofai", Crofai);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_crusoe>("crusoe", Crusoe);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_deepinfra>("deepinfra", Deepinfra);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_deepseek>("deepseek", Deepseek);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_dekallm>("dekallm", Dekallm);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_enfer>("enfer", Enfer);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_fakeProvider>("fake-provider", FakeProvider);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_featherless>("featherless", Featherless);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_fireworks>("fireworks", Fireworks);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_friendli>("friendli", Friendli);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_gmicloud>("gmicloud", Gmicloud);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_googleAiStudio>("google-ai-studio", GoogleAiStudio);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_googleVertex>("google-vertex", GoogleVertex);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_gopomelo>("gopomelo", Gopomelo);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_groq>("groq", Groq);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_huggingface>("huggingface", Huggingface);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_hyperbolic>("hyperbolic", Hyperbolic);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_hyperbolicQuantized>("hyperbolic-quantized", HyperbolicQuantized);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_inception>("inception", Inception);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_inceptron>("inceptron", Inceptron);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_inferenceNet>("inference-net", InferenceNet);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_infermatic>("infermatic", Infermatic);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_inflection>("inflection", Inflection);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_inocloud>("inocloud", Inocloud);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ioNet>("io-net", IoNet);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ionstream>("ionstream", Ionstream);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_klusterai>("klusterai", Klusterai);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_lambda>("lambda", Lambda);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_lepton>("lepton", Lepton);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_liquid>("liquid", Liquid);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_lynn>("lynn", Lynn);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_lynnPrivate>("lynn-private", LynnPrivate);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_mancer>("mancer", Mancer);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_mancerOld>("mancer-old", MancerOld);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_mara>("mara", Mara);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_meta>("meta", Meta);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_minimax>("minimax", Minimax);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_mistral>("mistral", Mistral);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_modal>("modal", Modal);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_modelrun>("modelrun", Modelrun);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_modular>("modular", Modular);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_moonshotai>("moonshotai", Moonshotai);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_morph>("morph", Morph);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ncompass>("ncompass", Ncompass);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_nebius>("nebius", Nebius);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_nexAgi>("nex-agi", NexAgi);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_nextbit>("nextbit", Nextbit);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_nineteen>("nineteen", Nineteen);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_novita>("novita", Novita);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_nvidia>("nvidia", Nvidia);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_octoai>("octoai", Octoai);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_openai>("openai", Openai);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_openInference>("open-inference", OpenInference);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_parasail>("parasail", Parasail);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_perplexity>("perplexity", Perplexity);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_phala>("phala", Phala);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_poolside>("poolside", Poolside);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_recraft>("recraft", Recraft);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_recursal>("recursal", Recursal);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_reflection>("reflection", Reflection);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_reka>("reka", Reka);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_relace>("relace", Relace);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_replicate>("replicate", Replicate);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_sambanova>("sambanova", Sambanova);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_sambanovaCloaked>("sambanova-cloaked", SambanovaCloaked);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_seed>("seed", Seed);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_sfCompute>("sf-compute", SfCompute);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_siliconflow>("siliconflow", Siliconflow);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_sourceful>("sourceful", Sourceful);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_stealth>("stealth", Stealth);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_stepfun>("stepfun", Stepfun);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_streamlake>("streamlake", Streamlake);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_switchpoint>("switchpoint", Switchpoint);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_targon>("targon", Targon);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_together>("together", Together);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_togetherLite>("together-lite", TogetherLite);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ubicloud>("ubicloud", Ubicloud);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_upstage>("upstage", Upstage);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_venice>("venice", Venice);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_wandb>("wandb", Wandb);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_xai>("xai", Xai);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_xiaomi>("xiaomi", Xiaomi);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_zAi>("z-ai", ZAi);
            writer.WriteObjectValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ProviderOptions_ZeroOneai>("01ai", ZeroOneai);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
