// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    /// <summary>
    /// Output from a shell command execution (newer variant)
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ShellCallOutputItem : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The call_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallId { get; set; }
#nullable restore
#else
        public string CallId { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The max_output_length property</summary>
        public int? MaxOutputLength { get; set; }
        /// <summary>The output property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenRouter.OpenApiClient.Models.ShellCallOutputItem_output>? Output { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenRouter.OpenApiClient.Models.ShellCallOutputItem_output> Output { get; set; }
#endif
        /// <summary>The status property</summary>
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ToolCallStatus? Status { get; set; }
        /// <summary>The type property</summary>
        public global::Soenneker.OpenRouter.OpenApiClient.Models.ShellCallOutputItem_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ShellCallOutputItem"/> and sets the default values.
        /// </summary>
        public ShellCallOutputItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenRouter.OpenApiClient.Models.ShellCallOutputItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenRouter.OpenApiClient.Models.ShellCallOutputItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenRouter.OpenApiClient.Models.ShellCallOutputItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "call_id", n => { CallId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "max_output_length", n => { MaxOutputLength = n.GetIntValue(); } },
                { "output", n => { Output = n.GetCollectionOfObjectValues<global::Soenneker.OpenRouter.OpenApiClient.Models.ShellCallOutputItem_output>(global::Soenneker.OpenRouter.OpenApiClient.Models.ShellCallOutputItem_output.CreateFromDiscriminatorValue)?.AsList(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ToolCallStatus>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ShellCallOutputItem_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("call_id", CallId);
            writer.WriteStringValue("id", Id);
            writer.WriteIntValue("max_output_length", MaxOutputLength);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenRouter.OpenApiClient.Models.ShellCallOutputItem_output>("output", Output);
            writer.WriteEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ToolCallStatus>("status", Status);
            writer.WriteEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Models.ShellCallOutputItem_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
