// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum StopServerToolsWhenStepCountIs_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "step_count_is")]
        #pragma warning disable CS1591
        Step_count_is,
        #pragma warning restore CS1591
    }
}
