// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    /// <summary>Aspect ratio of the generated video</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum VideoGenerationRequest_aspect_ratio
    {
        [EnumMember(Value = "16:9")]
        #pragma warning disable CS1591
        OneSixNine,
        #pragma warning restore CS1591
        [EnumMember(Value = "9:16")]
        #pragma warning disable CS1591
        NineOneSix,
        #pragma warning restore CS1591
        [EnumMember(Value = "1:1")]
        #pragma warning disable CS1591
        OneOne,
        #pragma warning restore CS1591
        [EnumMember(Value = "4:3")]
        #pragma warning disable CS1591
        FourThree,
        #pragma warning restore CS1591
        [EnumMember(Value = "3:4")]
        #pragma warning disable CS1591
        ThreeFour,
        #pragma warning restore CS1591
        [EnumMember(Value = "21:9")]
        #pragma warning disable CS1591
        TwoOneNine,
        #pragma warning restore CS1591
        [EnumMember(Value = "9:21")]
        #pragma warning disable CS1591
        NineTwoOne,
        #pragma warning restore CS1591
    }
}
