// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Models
{
    /// <summary>Resolution of the generated video</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum VideoGenerationRequest_resolution
    {
        [EnumMember(Value = "480p")]
        #pragma warning disable CS1591
        FourEightZerop,
        #pragma warning restore CS1591
        [EnumMember(Value = "720p")]
        #pragma warning disable CS1591
        SevenTwoZerop,
        #pragma warning restore CS1591
        [EnumMember(Value = "1080p")]
        #pragma warning disable CS1591
        OneZeroEightZerop,
        #pragma warning restore CS1591
        [EnumMember(Value = "1K")]
        #pragma warning disable CS1591
        OneK,
        #pragma warning restore CS1591
        [EnumMember(Value = "2K")]
        #pragma warning disable CS1591
        TwoK,
        #pragma warning restore CS1591
        [EnumMember(Value = "4K")]
        #pragma warning disable CS1591
        FourK,
        #pragma warning restore CS1591
    }
}
