// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.OpenRouter.OpenApiClient.Generation
{
    /// <summary>
    /// Generation data
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GenerationGetResponse_data : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Type of API used for the generation</summary>
        public global::Soenneker.OpenRouter.OpenApiClient.Generation.GenerationGetResponse_data_api_type? ApiType { get; set; }
        /// <summary>ID of the app that made the request</summary>
        public double? AppId { get; set; }
        /// <summary>Discount applied due to caching</summary>
        public double? CacheDiscount { get; set; }
        /// <summary>Whether the generation was cancelled</summary>
        public bool? Cancelled { get; set; }
        /// <summary>ISO 8601 timestamp of when the generation was created</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>External user identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalUser { get; set; }
#nullable restore
#else
        public string ExternalUser { get; set; }
#endif
        /// <summary>Reason the generation finished</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FinishReason { get; set; }
#nullable restore
#else
        public string FinishReason { get; set; }
#endif
        /// <summary>Time taken for generation in milliseconds</summary>
        public double? GenerationTime { get; set; }
        /// <summary>Referer header from the request</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HttpReferer { get; set; }
#nullable restore
#else
        public string HttpReferer { get; set; }
#endif
        /// <summary>Unique identifier for the generation</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Whether this used bring-your-own-key</summary>
        public bool? IsByok { get; set; }
        /// <summary>Total latency in milliseconds</summary>
        public double? Latency { get; set; }
        /// <summary>Model used for the generation</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>Moderation latency in milliseconds</summary>
        public double? ModerationLatency { get; set; }
        /// <summary>Native finish reason as reported by provider</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NativeFinishReason { get; set; }
#nullable restore
#else
        public string NativeFinishReason { get; set; }
#endif
        /// <summary>Native cached tokens as reported by provider</summary>
        public double? NativeTokensCached { get; set; }
        /// <summary>Native completion tokens as reported by provider</summary>
        public double? NativeTokensCompletion { get; set; }
        /// <summary>Native completion image tokens as reported by provider</summary>
        public double? NativeTokensCompletionImages { get; set; }
        /// <summary>Native prompt tokens as reported by provider</summary>
        public double? NativeTokensPrompt { get; set; }
        /// <summary>Native reasoning tokens as reported by provider</summary>
        public double? NativeTokensReasoning { get; set; }
        /// <summary>Number of audio inputs in the prompt</summary>
        public double? NumInputAudioPrompt { get; set; }
        /// <summary>Number of media items in the completion</summary>
        public double? NumMediaCompletion { get; set; }
        /// <summary>Number of media items in the prompt</summary>
        public double? NumMediaPrompt { get; set; }
        /// <summary>Number of search results included</summary>
        public double? NumSearchResults { get; set; }
        /// <summary>Origin URL of the request</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Origin { get; set; }
#nullable restore
#else
        public string Origin { get; set; }
#endif
        /// <summary>Name of the provider that served the request</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProviderName { get; set; }
#nullable restore
#else
        public string ProviderName { get; set; }
#endif
        /// <summary>List of provider responses for this generation, including fallback attempts</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.OpenRouter.OpenApiClient.Generation.GenerationGetResponse_data_provider_responses>? ProviderResponses { get; set; }
#nullable restore
#else
        public List<global::Soenneker.OpenRouter.OpenApiClient.Generation.GenerationGetResponse_data_provider_responses> ProviderResponses { get; set; }
#endif
        /// <summary>Unique identifier grouping all generations from a single API request</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RequestId { get; set; }
#nullable restore
#else
        public string RequestId { get; set; }
#endif
        /// <summary>Router used for the request (e.g., openrouter/auto)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Router { get; set; }
#nullable restore
#else
        public string Router { get; set; }
#endif
        /// <summary>Whether the response was streamed</summary>
        public bool? Streamed { get; set; }
        /// <summary>Number of tokens in the completion</summary>
        public double? TokensCompletion { get; set; }
        /// <summary>Number of tokens in the prompt</summary>
        public double? TokensPrompt { get; set; }
        /// <summary>Total cost of the generation in USD</summary>
        public double? TotalCost { get; set; }
        /// <summary>Upstream provider&apos;s identifier for this generation</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpstreamId { get; set; }
#nullable restore
#else
        public string UpstreamId { get; set; }
#endif
        /// <summary>Cost charged by the upstream provider</summary>
        public double? UpstreamInferenceCost { get; set; }
        /// <summary>Usage amount in USD</summary>
        public double? Usage { get; set; }
        /// <summary>User-Agent header from the request</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserAgent { get; set; }
#nullable restore
#else
        public string UserAgent { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.OpenRouter.OpenApiClient.Generation.GenerationGetResponse_data"/> and sets the default values.
        /// </summary>
        public GenerationGetResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.OpenRouter.OpenApiClient.Generation.GenerationGetResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.OpenRouter.OpenApiClient.Generation.GenerationGetResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.OpenRouter.OpenApiClient.Generation.GenerationGetResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "api_type", n => { ApiType = n.GetEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Generation.GenerationGetResponse_data_api_type>(); } },
                { "app_id", n => { AppId = n.GetDoubleValue(); } },
                { "cache_discount", n => { CacheDiscount = n.GetDoubleValue(); } },
                { "cancelled", n => { Cancelled = n.GetBoolValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "external_user", n => { ExternalUser = n.GetStringValue(); } },
                { "finish_reason", n => { FinishReason = n.GetStringValue(); } },
                { "generation_time", n => { GenerationTime = n.GetDoubleValue(); } },
                { "http_referer", n => { HttpReferer = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "is_byok", n => { IsByok = n.GetBoolValue(); } },
                { "latency", n => { Latency = n.GetDoubleValue(); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "moderation_latency", n => { ModerationLatency = n.GetDoubleValue(); } },
                { "native_finish_reason", n => { NativeFinishReason = n.GetStringValue(); } },
                { "native_tokens_cached", n => { NativeTokensCached = n.GetDoubleValue(); } },
                { "native_tokens_completion", n => { NativeTokensCompletion = n.GetDoubleValue(); } },
                { "native_tokens_completion_images", n => { NativeTokensCompletionImages = n.GetDoubleValue(); } },
                { "native_tokens_prompt", n => { NativeTokensPrompt = n.GetDoubleValue(); } },
                { "native_tokens_reasoning", n => { NativeTokensReasoning = n.GetDoubleValue(); } },
                { "num_input_audio_prompt", n => { NumInputAudioPrompt = n.GetDoubleValue(); } },
                { "num_media_completion", n => { NumMediaCompletion = n.GetDoubleValue(); } },
                { "num_media_prompt", n => { NumMediaPrompt = n.GetDoubleValue(); } },
                { "num_search_results", n => { NumSearchResults = n.GetDoubleValue(); } },
                { "origin", n => { Origin = n.GetStringValue(); } },
                { "provider_name", n => { ProviderName = n.GetStringValue(); } },
                { "provider_responses", n => { ProviderResponses = n.GetCollectionOfObjectValues<global::Soenneker.OpenRouter.OpenApiClient.Generation.GenerationGetResponse_data_provider_responses>(global::Soenneker.OpenRouter.OpenApiClient.Generation.GenerationGetResponse_data_provider_responses.CreateFromDiscriminatorValue)?.AsList(); } },
                { "request_id", n => { RequestId = n.GetStringValue(); } },
                { "router", n => { Router = n.GetStringValue(); } },
                { "streamed", n => { Streamed = n.GetBoolValue(); } },
                { "tokens_completion", n => { TokensCompletion = n.GetDoubleValue(); } },
                { "tokens_prompt", n => { TokensPrompt = n.GetDoubleValue(); } },
                { "total_cost", n => { TotalCost = n.GetDoubleValue(); } },
                { "upstream_id", n => { UpstreamId = n.GetStringValue(); } },
                { "upstream_inference_cost", n => { UpstreamInferenceCost = n.GetDoubleValue(); } },
                { "usage", n => { Usage = n.GetDoubleValue(); } },
                { "user_agent", n => { UserAgent = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.OpenRouter.OpenApiClient.Generation.GenerationGetResponse_data_api_type>("api_type", ApiType);
            writer.WriteDoubleValue("app_id", AppId);
            writer.WriteDoubleValue("cache_discount", CacheDiscount);
            writer.WriteBoolValue("cancelled", Cancelled);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteStringValue("external_user", ExternalUser);
            writer.WriteStringValue("finish_reason", FinishReason);
            writer.WriteDoubleValue("generation_time", GenerationTime);
            writer.WriteStringValue("http_referer", HttpReferer);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("is_byok", IsByok);
            writer.WriteDoubleValue("latency", Latency);
            writer.WriteStringValue("model", Model);
            writer.WriteDoubleValue("moderation_latency", ModerationLatency);
            writer.WriteStringValue("native_finish_reason", NativeFinishReason);
            writer.WriteDoubleValue("native_tokens_cached", NativeTokensCached);
            writer.WriteDoubleValue("native_tokens_completion", NativeTokensCompletion);
            writer.WriteDoubleValue("native_tokens_completion_images", NativeTokensCompletionImages);
            writer.WriteDoubleValue("native_tokens_prompt", NativeTokensPrompt);
            writer.WriteDoubleValue("native_tokens_reasoning", NativeTokensReasoning);
            writer.WriteDoubleValue("num_input_audio_prompt", NumInputAudioPrompt);
            writer.WriteDoubleValue("num_media_completion", NumMediaCompletion);
            writer.WriteDoubleValue("num_media_prompt", NumMediaPrompt);
            writer.WriteDoubleValue("num_search_results", NumSearchResults);
            writer.WriteStringValue("origin", Origin);
            writer.WriteStringValue("provider_name", ProviderName);
            writer.WriteCollectionOfObjectValues<global::Soenneker.OpenRouter.OpenApiClient.Generation.GenerationGetResponse_data_provider_responses>("provider_responses", ProviderResponses);
            writer.WriteStringValue("request_id", RequestId);
            writer.WriteStringValue("router", Router);
            writer.WriteBoolValue("streamed", Streamed);
            writer.WriteDoubleValue("tokens_completion", TokensCompletion);
            writer.WriteDoubleValue("tokens_prompt", TokensPrompt);
            writer.WriteDoubleValue("total_cost", TotalCost);
            writer.WriteStringValue("upstream_id", UpstreamId);
            writer.WriteDoubleValue("upstream_inference_cost", UpstreamInferenceCost);
            writer.WriteDoubleValue("usage", Usage);
            writer.WriteStringValue("user_agent", UserAgent);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
